---
permalink: sg6000/configuring-bmc-interface-sg6000.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, sg6000-cn, storage node, storage appliance, BMC, baseboard management controller, configure, setup, set up 
summary: 'L"interface utilisateur du contrôleur de gestion de la carte mère \(BMC\) du contrôleur SG6000-CN fournit des informations d"état sur le matériel et vous permet de configurer les paramètres SNMP et d"autres options pour le contrôleur SG6000-CN.' 
---
= Configuration de l'interface BMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interface utilisateur du contrôleur de gestion de la carte mère (BMC) du contrôleur SG6000-CN fournit des informations d'état sur le matériel et permet de configurer les paramètres SNMP et d'autres options pour le contrôleur SG6000-CN.

.Étapes
* link:changing-root-password-for-bmc-interface-sg6000.html["Modification du mot de passe racine de l'interface BMC"]
* link:setting-ip-address-for-bmc-management-port-sg6000.html["Définition de l'adresse IP du port de gestion BMC"]
* link:accessing-bmc-interface-sg6000.html["Accès à l'interface BMC"]
* link:configuring-snmp-settings-for-sg6000-cn-controller.html["Configuration des paramètres SNMP pour le contrôleur SG6000-CN"]
* link:setting-up-email-notifications-for-alerts.html["Configuration des notifications par e-mail pour les alertes"]

