---
permalink: sg6000/configuring-storagegrid-connections.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, storagegrid connections, connections, configure, setup, set up 
summary: 'Avant de déployer une appliance StorageGRID en tant que nœud de stockage dans un système StorageGRID, vous devez configurer les connexions entre l"appliance et les réseaux que vous prévoyez d"utiliser. Vous pouvez configurer la mise en réseau en accédant au programme d"installation de l"appliance StorageGRID, qui est préinstallé sur le contrôleur SG6000-CN \(le contrôleur de calcul\).' 
---
= Configuration des connexions StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de déployer une appliance StorageGRID en tant que nœud de stockage dans un système StorageGRID, vous devez configurer les connexions entre l'appliance et les réseaux que vous prévoyez d'utiliser. Vous pouvez configurer la mise en réseau en accédant au programme d'installation de l'appliance StorageGRID, qui est préinstallé sur le contrôleur SG6000-CN (le contrôleur de calcul).

.Étapes
* link:accessing-storagegrid-appliance-installer-sg6000.html["Accès au programme d'installation de l'appliance StorageGRID"]
* link:verifying-and-upgrading-storagegrid-appliance-installer-version.html["Vérification et mise à niveau de la version du programme d'installation de l'appliance StorageGRID"]
* link:configuring-network-links-sg6000.html["Configuration des liaisons réseau (SG6000)"]
* link:configuring-storagegrid-ip-addresses-sg6000.html["Configuration des adresses IP StorageGRID"]
* link:verifying-network-connections.html["Vérification des connexions réseau"]
* link:verifying-port-level-network-connections.html["Vérification des connexions réseau au niveau des ports"]

