---
permalink: sg6000/preparing-for-installation.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, install, installation, preparation, get ready, prepare 
summary: 'La préparation de l"installation d"une appliance StorageGRID implique de préparer le site et d"obtenir l"ensemble du matériel, des câbles et des outils requis. Vous devez également collecter les adresses IP et les informations réseau.' 
---
= Préparation de l'installation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La préparation de l'installation d'une appliance StorageGRID implique de préparer le site et d'obtenir l'ensemble du matériel, des câbles et des outils requis. Vous devez également collecter les adresses IP et les informations réseau.

.Étapes
* link:preparing-site-sg6000.html["Préparation du site (SG6000)"]
* link:unpacking-boxes-sg6000.html["Déballage des boîtes (SG6000)"]
* link:obtaining-additional-equipment-and-tools-sg6000.html["Obtention d'équipements et d'outils supplémentaires (SG6000)"]
* link:web-browser-requirements.html["Navigateurs Web pris en charge"]
* link:reviewing-appliance-network-connections-sg6000.html["Vérification des connexions réseau de l'appliance"]
* link:gathering-installation-information-sg6000.html["Collecte des informations d'installation (SG6000)"]

