---
settings:
  name: StorageGRID 11.5
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: StorageGRID 11.5 Docs
    url: "/index.html"
  - section: release-notes
  - title: Commencez
    entries:
    - section: primer
    - section: network
  - title: Installez et mettez à niveau le logiciel
    entries:
    - section: rhel
    - section: ubuntu
    - section: vmware
    - section: upgrade
  - title: Installer et entretenir le matériel
    entries:
    - section: sg6000
    - section: sg5700
    - section: sg5600
    - section: sg100-1000
  - title: Configurez et gérez
    entries:
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
  - title: Utiliser StorageGRID
    entries:
    - section: tenant
    - section: s3
    - section: swift
  - title: Surveiller et résoudre les problèmes
    entries:
    - section: monitor
    - section: troubleshoot
    - section: audit
  - title: Maintenance
    entries:
    - section: expand
    - section: maintain
  - title: Autres versions
    url: "/earlier-versions.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family
