---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, firewall, ports 
summary: Avant de mettre à niveau un système StorageGRID, vous devez vérifier que celui-ci est prêt à effectuer la mise à niveau. Vous devez vous assurer que le système fonctionne normalement et que tous les nœuds de la grille sont opérationnels. 
---
= Vérification de l'état du système avant la mise à niveau du logiciel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de mettre à niveau un système StorageGRID, vous devez vérifier que celui-ci est prêt à effectuer la mise à niveau. Vous devez vous assurer que le système fonctionne normalement et que tous les nœuds de la grille sont opérationnels.

.Étapes
. Connectez-vous au Grid Manager à l'aide d'un navigateur pris en charge.
. Recherchez et résolvez les alertes actives.
+
Pour plus d'informations sur des alertes spécifiques, reportez-vous aux instructions de surveillance et de dépannage.

. Confirmez qu'aucune tâche de grille en conflit n'est active ou en attente.
+
.. Sélectionnez *support* > *Outils* > *topologie de grille*.
.. Sélectionnez *_site_* > *_primary Admin Node_* > *CMN* > *Grid Tasks* > *Configuration*.
+
Les tâches d'évaluation de la gestion du cycle de vie des informations (IDME) sont les seules tâches de grille pouvant être exécutées simultanément avec la mise à niveau logicielle.

.. Si d'autres tâches de grille sont actives ou en attente, attendez qu'elles aient terminé ou lâchés leur verrouillage.
+

NOTE: Contactez le support technique si une tâche ne se termine pas ou ne relâche pas son verrouillage.



. Reportez-vous aux listes des ports internes et externes de la version 11.5 des directives de mise en réseau et assurez-vous que tous les ports requis sont ouverts avant la mise à niveau.
+

IMPORTANT: Si vous avez ouvert des ports de pare-feu personnalisés, vous êtes averti au cours de la vérification préalable de la mise à niveau. Vous devez contacter le support technique avant de procéder à la mise à niveau.



.Informations associées
link:../monitor/index.html["Moniteur et amp ; dépannage"]

link:../admin/index.html["Administrer StorageGRID"]

link:../maintain/index.html["Maintenance et récupération"]

link:../network/index.html["Instructions réseau"]
