---
permalink: upgrade/downloading-recovery-package.html 
sidebar: sidebar 
keywords: recovery package, download 
summary: Le fichier progiciel de récupération vous permet de restaurer le système StorageGRID en cas de défaillance. 
---
= Téléchargement du progiciel de restauration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le fichier progiciel de récupération vous permet de restaurer le système StorageGRID en cas de défaillance.

.Ce dont vous avez besoin
* Vous devez être connecté à Grid Manager à l'aide d'un navigateur pris en charge.
* Vous devez disposer de la phrase secrète pour le provisionnement.
* Vous devez disposer d'autorisations d'accès spécifiques.


.Description de la tâche
Téléchargez le fichier du pack de récupération actuel avant de modifier la topologie du grid sur le système StorageGRID ou avant de mettre à niveau le logiciel. Téléchargez ensuite une nouvelle copie du progiciel de récupération après avoir modifié la topologie de la grille ou après la mise à niveau du logiciel.

.Étapes
. Sélectionnez *Maintenance* > *système* > *progiciel de récupération*.
. Saisissez le mot de passe de provisionnement et sélectionnez *Démarrer le téléchargement*.
+
Le téléchargement commence immédiatement.

. Une fois le téléchargement terminé :
+
.. Ouvrez le `.zip` fichier.
.. Vérifiez qu'elle inclut un `gpt-backup` et un intérieur `.zip` fichier.
.. Extraire l'intérieur `.zip` fichier.
.. Confirmez que vous pouvez ouvrir le `Passwords.txt` fichier.


. Copiez le fichier du progiciel de restauration téléchargé (`.zip`) à deux emplacements sûrs, sécurisés et séparés.
+

IMPORTANT: Le fichier du progiciel de récupération doit être sécurisé car il contient des clés de cryptage et des mots de passe qui peuvent être utilisés pour obtenir des données du système StorageGRID.



.Informations associées
link:../admin/index.html["Administrer StorageGRID"]
