---
permalink: sg100-1000/configuring-bmc-interface-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, BMC, baseboard management controller, configure, setup, set up 
summary: 'L"interface utilisateur du contrôleur de gestion de la carte mère \(BMC\) de l"appliance de services fournit des informations d"état sur le matériel et vous permet de configurer les paramètres SNMP et d"autres options pour l"appliance de services.' 
---
= Configuration de l'interface BMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interface utilisateur du contrôleur de gestion de la carte mère (BMC) de l'appliance de services fournit des informations d'état sur le matériel et vous permet de configurer les paramètres SNMP et d'autres options pour l'appliance de services.

.Étapes
* link:changing-root-password-for-bmc-interface-sg1000.html["Modification du mot de passe racine de l'interface BMC"]
* link:setting-ip-address-for-bmc-management-port-sg1000.html["Définition de l'adresse IP du port de gestion BMC"]
* link:accessing-bmc-interface-sg1000.html["Accès à l'interface BMC"]
* link:configuring-snmp-settings-for-sg1000.html["Configuration des paramètres SNMP pour l'appliance de services"]
* link:setting-up-email-notifications-for-alerts.html["Configuration des notifications par e-mail pour les alertes"]

