---
permalink: sg100-1000/reviewing-appliance-network-connections-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, network connections, network connection, network, connection, grid, admin, client, bmc, management 
summary: 'Avant d"installer l"appliance StorageGRID, vous devez savoir quels réseaux peuvent être connectés à l"appliance.' 
---
= Vérification des connexions réseau de l'appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'installer l'appliance StorageGRID, vous devez savoir quels réseaux peuvent être connectés à l'appliance.

Lorsque vous déployez une appliance StorageGRID en tant que nœud d'un système StorageGRID, vous pouvez la connecter aux réseaux suivants :

* *Réseau Grid pour StorageGRID* : le réseau Grid est utilisé pour tout le trafic StorageGRID interne. Il assure la connectivité entre tous les nœuds de la grille, sur tous les sites et sous-réseaux. Le réseau Grid est requis.
* *Réseau d'administration pour StorageGRID* : le réseau d'administration est un réseau fermé utilisé pour l'administration et la maintenance du système. Le réseau Admin est généralement un réseau privé et n'a pas besoin d'être routable entre les sites. Le réseau d'administration est facultatif.
* *Réseau client pour StorageGRID :* le réseau client est un réseau ouvert utilisé pour fournir un accès aux applications client, y compris S3 et Swift. Le réseau client fournit un accès au protocole client à la grille, de sorte que le réseau Grid puisse être isolé et sécurisé. Vous pouvez configurer le réseau client de sorte que l'appliance soit accessible via ce réseau en utilisant uniquement les ports que vous choisissez d'ouvrir. Le réseau client est facultatif.
* *Réseau de gestion BMC pour l'appliance de services :* ce réseau permet d'accéder au contrôleur de gestion de la carte mère des systèmes SG100 et SG1000, et permet de surveiller et de gérer les composants matériels de l'appliance. Ce réseau de gestion peut être le même que le réseau d'administration pour StorageGRID, ou il peut s'agir d'un réseau de gestion indépendant.


.Informations associées
link:gathering-installation-information-sg100-and-sg1000.html["Collecte des informations d'installation (SG100 et SG1000)"]

link:cabling-appliance-sg100-and-sg1000.html["Câblage de l'appareil SG100 et SG1000)"]

link:../network/index.html["Instructions réseau"]

link:../primer/index.html["Primaire de grille"]
