---
permalink: ubuntu/installation-overview.html 
sidebar: sidebar 
keywords:  
summary: 'L"installation d"un système StorageGRID dans un environnement Ubuntu ou Debian comprend trois étapes principales.' 
---
= Présentation de l'installation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'installation d'un système StorageGRID dans un environnement Ubuntu ou Debian comprend trois étapes principales.

. *Préparation*: Pendant la planification et la préparation, vous effectuez les tâches suivantes :
+
** En savoir plus sur les besoins matériels et de stockage pour StorageGRID.
** Découvrez en détail les caractéristiques du réseau StorageGRID afin que vous puissiez configurer votre réseau de façon appropriée. Pour plus d'informations, consultez les instructions de mise en réseau d'StorageGRID.
** Identifiez et préparez les serveurs physiques ou virtuels que vous prévoyez d'utiliser pour héberger vos nœuds de grid StorageGRID.
** Sur les serveurs que vous avez préparés :
+
*** Installez Ubuntu ou Debian
*** Configurez le réseau hôte
*** Configurer le stockage de l'hôte
*** Installez Docker
*** Installez les services d'hôte StorageGRID




. *Déploiement* : déployez des nœuds de la grille à l'aide de l'interface utilisateur appropriée. Lorsque vous déployez des nœuds grid, ils sont créés dans le cadre du système StorageGRID et connectés à un ou plusieurs réseaux.
+
.. Utilisez la ligne de commande Ubuntu ou Debian et les fichiers de configuration de nœud pour déployer des nœuds de grille virtuelle sur les hôtes que vous avez préparés à l'étape 1.
.. Utilisez le programme d'installation de l'appliance StorageGRID pour déployer les nœuds d'appliance StorageGRID.
+

NOTE: Des instructions d'installation et d'intégration spécifiques au matériel ne sont pas incluses dans la procédure d'installation de StorageGRID. Pour savoir comment installer des appliances StorageGRID, consultez les instructions d'installation et de maintenance de votre appareil.



. *Configuration* : lorsque tous les nœuds ont été déployés, utilisez le gestionnaire de grille pour configurer la grille et terminer l'installation.


Ces instructions recommandent une approche standard pour le déploiement et la configuration d'un système StorageGRID dans un environnement Ubuntu ou Debian. Voir également les informations sur les approches alternatives suivantes :

* Utilisez une structure d'orchestration standard telle qu'Ansible, Puppet ou Chef pour installer Ubuntu ou Debian, configurer la mise en réseau et le stockage, installer Docker et le service hôte StorageGRID, et déployer des nœuds de grid virtuel.
* Automatiser le déploiement et la configuration du système StorageGRID à l'aide d'un script de configuration Python (fourni dans l'archive d'installation).
* Automatisez le déploiement et la configuration des nœuds grid d'appliance avec un script de configuration Python (disponible dans l'archive de l'installation ou depuis le programme d'installation de l'appliance StorageGRID).
* Si vous êtes un développeur avancé de déploiements StorageGRID, utilisez les API REST d'installation pour automatiser l'installation des nœuds grid d'StorageGRID.


.Informations associées
link:planning-and-preparation.html["Planification et préparation"]

link:deploying-virtual-grid-nodes.html["Déploiement de nœuds grid virtuels"]

link:configuring-grid-and-completing-installation.html["Configuration de la grille et fin de l'installation"]

link:automating-installation-and-configuration-of-storagegrid-host-service.html["Automatisation de l'installation et de la configuration du service hôte StorageGRID"]

link:overview-of-installation-rest-api.html["Présentation de l'API REST d'installation"]

link:../network/index.html["Instructions réseau"]
