---
permalink: ubuntu/installing-linux.html 
sidebar: sidebar 
keywords:  
summary: 'Vous devez installer Ubuntu ou Debian sur tous les hôtes de la grille. Utilisez la matrice d"interopérabilité NetApp pour obtenir la liste des versions prises en charge.' 
---
= Installation de Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez installer Ubuntu ou Debian sur tous les hôtes de la grille. Utilisez la matrice d'interopérabilité NetApp pour obtenir la liste des versions prises en charge.

.Étapes
. Installez Ubuntu ou Debian sur tous les hôtes de la grille physique ou virtuelle conformément aux instructions du distributeur ou à votre procédure standard.
+

NOTE: N'installez pas d'environnement de bureau graphique. Lors de l'installation d'Ubuntu, vous devez sélectionner *utilitaires système standard*. La sélection de *OpenSSH Server* est recommandée pour activer l'accès ssh à vos hôtes Ubuntu. Toutes les autres options peuvent rester désélectionnées.

. Assurez-vous que tous les hôtes ont accès aux référentiels de paquets Ubuntu ou Debian.
. Si le swap est activé :
+
.. Exécutez la commande suivante : `$ sudo swapoff --all`
.. Supprimez toutes les entrées d'échange de `/etc/fstab` pour conserver les paramètres.


+

IMPORTANT: Si vous ne désactivez pas ces fichiers, les performances peuvent être considérablement réduites.



.Informations associées
https://["Matrice d'interopérabilité NetApp"^]
