---
permalink: ubuntu/required-materials.html 
sidebar: sidebar 
keywords:  
summary: 'Avant d"installer StorageGRID, vous devez rassembler et préparer les ressources nécessaires.' 
---
= Matériel requis
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'installer StorageGRID, vous devez rassembler et préparer les ressources nécessaires.

|===
| Élément | Remarques 


 a| 
Licence NetApp StorageGRID
 a| 
Vous devez disposer d'une licence NetApp valide et signée numériquement.

*Note*: Une licence de non-production, qui peut être utilisée pour tester et démontrer les grilles de concept, est incluse dans l'archive d'installation de StorageGRID.



 a| 
Archive de l'installation de StorageGRID
 a| 
Vous devez télécharger l'archive d'installation de StorageGRID et extraire les fichiers.



 a| 
L'ordinateur portable de service
 a| 
Le système StorageGRID est installé par le biais d'un ordinateur portable de service.

L'ordinateur portable de service doit posséder :

* Port réseau
* Client SSH (par exemple, PuTTY)
* Navigateur Web pris en charge




 a| 
Documentation StorageGRID
 a| 
* Notes de mise à jour
* Instructions d'administration de StorageGRID


|===
.Informations associées
link:downloading-and-extracting-storagegrid-installation-files.html["Téléchargement et extraction des fichiers d'installation de StorageGRID"]

link:web-browser-requirements.html["Navigateurs Web pris en charge"]

link:../admin/index.html["Administrer StorageGRID"]

link:../release-notes/index.html["Notes de mise à jour"]
