---
permalink: network/external-communications.html 
sidebar: sidebar 
keywords: storagegrid, network port, external communications, ports, TCP, UDP, client communications 
summary: Les clients doivent communiquer avec les nœuds du grid pour ingérer et récupérer le contenu. Les ports utilisés dépendent des protocoles de stockage objet choisis. Ces ports doivent être accessibles au client. 
---
= Communications externes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les clients doivent communiquer avec les nœuds du grid pour ingérer et récupérer le contenu. Les ports utilisés dépendent des protocoles de stockage objet choisis. Ces ports doivent être accessibles au client.

Si les stratégies de mise en réseau d'entreprise limitent l'accès à l'un des ports, vous pouvez utiliser les points finaux de l'équilibreur de charge pour autoriser l'accès aux ports définis par l'utilisateur. La fonction réseaux clients non fiables peut être utilisée pour autoriser l'accès uniquement sur les ports de point de terminaison de l'équilibreur de charge.


NOTE: Pour utiliser des systèmes et des protocoles tels que SMTP, DNS, SSH ou DHCP, vous devez remappage les ports lors du déploiement des nœuds. Toutefois, vous ne devez pas remaper les terminaux d'équilibrage. Pour plus d'informations sur le remappage des ports, reportez-vous aux instructions d'installation de votre plate-forme.

Le tableau suivant indique les ports utilisés pour le trafic dans les nœuds.


NOTE: Cette liste ne comprend pas les ports qui peuvent être configurés en tant que noeuds finaux de l'équilibreur de charge. Pour plus d'informations, reportez-vous aux instructions de configuration des noeuds finaux de l'équilibreur de charge.

[cols="1a,1a,1a,1a,1a,2a"]
|===
| Port | TCP ou UDP | Protocole | De | À | Détails 


 a| 
22
 a| 
TCP
 a| 
SSH
 a| 
L'ordinateur portable de service
 a| 
Tous les nœuds
 a| 
Un accès SSH ou via la console est requis pour les procédures liées aux étapes de la console. Vous pouvez également utiliser le port 2022 au lieu de 22.



 a| 
25
 a| 
TCP
 a| 
SMTP
 a| 
Nœuds d'administration
 a| 
Serveur de messagerie
 a| 
Utilisé pour les alertes et l'adresse AutoSupport basée sur des e-mails. Vous pouvez remplacer le paramètre de port par défaut de 25 à l'aide de la page serveurs de messagerie.



 a| 
53
 a| 
TCP/UDP
 a| 
DNS
 a| 
Tous les nœuds
 a| 
Serveurs DNS
 a| 
Utilisé pour le système de noms de domaine.



 a| 
67
 a| 
UDP
 a| 
DHCP
 a| 
Tous les nœuds
 a| 
Service DHCP
 a| 
Permet de prendre en charge la configuration réseau basée sur DHCP. Le service dhclient ne fonctionne pas pour les grilles configurées de façon statique.



 a| 
68
 a| 
UDP
 a| 
DHCP
 a| 
Service DHCP
 a| 
Tous les nœuds
 a| 
Permet de prendre en charge la configuration réseau basée sur DHCP. Le service dhclient ne s'exécute pas pour les grilles qui utilisent des adresses IP statiques.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Navigateur
 a| 
Nœuds d'administration
 a| 
Le port 80 redirige vers le port 443 pour l'interface utilisateur du nœud d'administration.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Navigateur
 a| 
Appliances
 a| 
Le port 80 redirige vers le port 8443 du programme d'installation de l'appliance StorageGRID.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Nœuds de stockage avec ADC
 a| 
AWS
 a| 
Utilisé pour les messages de services de plateforme envoyés à AWS ou à d'autres services externes utilisant HTTP. Les locataires peuvent remplacer le paramètre de port HTTP par défaut de 80 lors de la création d'un noeud final.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Nœuds de stockage
 a| 
AWS
 a| 
Demandes de pools de stockage cloud envoyées aux cibles AWS utilisant HTTP. Les administrateurs du grid peuvent remplacer le paramètre de port HTTP par défaut de 80 lors de la configuration d'un pool de stockage cloud.



 a| 
111
 a| 
TCP/UDP
 a| 
Rpcbind
 a| 
Client NFS
 a| 
Nœuds d'administration
 a| 
Utilisé par l'export d'audit basé sur NFS (portmap).

*Remarque :* ce port n'est nécessaire que si l'exportation d'audit NFS est activée.



 a| 
123
 a| 
UDP
 a| 
NTP
 a| 
Nœuds NTP principaux
 a| 
NTP externe
 a| 
Service de protocole de temps de réseau. Les nœuds sélectionnés comme sources NTP principales synchronisent également les heures d'horloge avec les sources d'heure NTP externes.



 a| 
137
 a| 
UDP
 a| 
NetBIOS
 a| 
Client SMB
 a| 
Nœuds d'administration
 a| 
Utilisé par l'exportation d'audit SMB pour les clients nécessitant la prise en charge NetBIOS.

*Remarque :* ce port n'est requis que si l'exportation d'audit SMB est activée.



 a| 
138
 a| 
UDP
 a| 
NetBIOS
 a| 
Client SMB
 a| 
Nœuds d'administration
 a| 
Utilisé par l'exportation d'audit SMB pour les clients nécessitant la prise en charge NetBIOS.

*Remarque :* ce port n'est requis que si l'exportation d'audit SMB est activée.



 a| 
139
 a| 
TCP
 a| 
PME
 a| 
Client SMB
 a| 
Nœuds d'administration
 a| 
Utilisé par l'exportation d'audit SMB pour les clients nécessitant la prise en charge NetBIOS.

*Remarque :* ce port n'est requis que si l'exportation d'audit SMB est activée.



 a| 
161
 a| 
TCP/UDP
 a| 
SNMP
 a| 
Client SNMP
 a| 
Tous les nœuds
 a| 
Utilisé pour l'interrogation SNMP. Tous les nœuds fournissent des informations de base ; les nœuds d'administration fournissent également des données d'alerte et d'alarme. Le port UDP 161 est défini par défaut lorsqu'il est configuré.

*Remarque :* ce port n'est nécessaire que, et n'est ouvert que sur le pare-feu de nœud si SNMP est configuré. Si vous prévoyez d'utiliser SNMP, vous pouvez configurer d'autres ports.

*Remarque :* pour plus d'informations sur l'utilisation de SNMP avec StorageGRID, contactez votre ingénieur commercial NetApp.



 a| 
162
 a| 
TCP/UDP
 a| 
Notifications SNMP
 a| 
Tous les nœuds
 a| 
Destinations de notification
 a| 
Notifications et interruptions SNMP sortantes par défaut au port UDP 162.

*Remarque :* ce port n'est requis que si SNMP est activé et que les destinations de notification sont configurées. Si vous prévoyez d'utiliser SNMP, vous pouvez configurer d'autres ports.

*Remarque :* pour plus d'informations sur l'utilisation de SNMP avec StorageGRID, contactez votre ingénieur commercial NetApp.



 a| 
389
 a| 
TCP/UDP
 a| 
LDAP
 a| 
Nœuds de stockage avec ADC
 a| 
Active Directory/LDAP
 a| 
Utilisé pour la connexion à un serveur Active Directory ou LDAP pour la fédération des identités.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Navigateur
 a| 
Nœuds d'administration
 a| 
Utilisé par les navigateurs Web et les clients API de gestion pour accéder à Grid Manager et tenant Manager.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Nœuds d'administration
 a| 
Active Directory
 a| 
Utilisé par les nœuds d'administration se connectant à Active Directory si l'authentification unique (SSO) est activée.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Nœuds d'archivage
 a| 
Amazon S3
 a| 
Utilisé pour accéder à Amazon S3 à partir des nœuds d'archivage.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Nœuds de stockage avec ADC
 a| 
AWS
 a| 
Utilisé pour les messages de services de plateforme envoyés à AWS ou à d'autres services externes utilisant HTTPS. Les locataires peuvent remplacer le paramètre de port HTTP par défaut de 443 lors de la création d'un noeud final.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Nœuds de stockage
 a| 
AWS
 a| 
Les demandes de pools de stockage cloud sont envoyées aux cibles AWS qui utilisent HTTPS. Les administrateurs du grid peuvent remplacer le paramètre de port HTTPS par défaut de 443 lors de la configuration d'un pool de stockage cloud.



 a| 
445
 a| 
TCP
 a| 
PME
 a| 
Client SMB
 a| 
Nœuds d'administration
 a| 
Utilisé par l'exportation d'audit basée sur SMB.

*Remarque :* ce port n'est requis que si l'exportation d'audit SMB est activée.



 a| 
903
 a| 
TCP
 a| 
NFS
 a| 
Client NFS
 a| 
Nœuds d'administration
 a| 
Utilisé par l'exportation d'audit basée sur NFS (`rpc.mountd`).

*Remarque :* ce port n'est nécessaire que si l'exportation d'audit NFS est activée.



 a| 
2022
 a| 
TCP
 a| 
SSH
 a| 
L'ordinateur portable de service
 a| 
Tous les nœuds
 a| 
Un accès SSH ou via la console est requis pour les procédures liées aux étapes de la console. Vous pouvez également utiliser le port 22 au lieu de 2022.



 a| 
2049
 a| 
TCP
 a| 
NFS
 a| 
Client NFS
 a| 
Nœuds d'administration
 a| 
Utilisé par l'export d'audit basé sur NFS (nfs).

*Remarque :* ce port n'est nécessaire que si l'exportation d'audit NFS est activée.



 a| 
5696
 a| 
TCP
 a| 
KMIP
 a| 
Appliance
 a| 
KM
 a| 
Trafic externe KMIP (Key Management Interoperability Protocol) depuis les appliances configurées pour le chiffrement des nœuds vers le serveur de gestion des clés (KMS), sauf si un autre port est spécifié sur la page de configuration KMS du programme d'installation de l'appliance StorageGRID.



 a| 
8022
 a| 
TCP
 a| 
SSH
 a| 
L'ordinateur portable de service
 a| 
Tous les nœuds
 a| 
SSH sur le port 8022 permet d'accéder au système d'exploitation de base sur l'appliance et les plateformes de nœuds virtuels pour le support et le dépannage. Ce port n'est pas utilisé pour les nœuds Linux (bare Metal) et n'est pas requis pour être accessible entre les nœuds de la grille ou pendant les opérations normales.



 a| 
8082
 a| 
TCP
 a| 
HTTPS
 a| 
Clients S3
 a| 
Nœuds de passerelle
 a| 
Trafic externe lié à S3 vers les nœuds de passerelle (HTTPS).



 a| 
8083
 a| 
TCP
 a| 
HTTPS
 a| 
Clients Swift
 a| 
Nœuds de passerelle
 a| 
Trafic externe lié à Swift vers les nœuds de passerelle (HTTPS).



 a| 
8084
 a| 
TCP
 a| 
HTTP
 a| 
Clients S3
 a| 
Nœuds de passerelle
 a| 
Trafic externe lié à S3 vers les nœuds de passerelle (HTTP).



 a| 
8085
 a| 
TCP
 a| 
HTTP
 a| 
Clients Swift
 a| 
Nœuds de passerelle
 a| 
Trafic externe lié à Swift vers les nœuds de passerelle (HTTP).



 a| 
8443
 a| 
TCP
 a| 
HTTPS
 a| 
Navigateur
 a| 
Nœuds d'administration
 a| 
Facultatif. Utilisé par les navigateurs Web et les clients API de gestion pour accéder à Grid Manager. Peut être utilisé pour séparer les communications Grid Manager et tenant Manager.



 a| 
9022
 a| 
TCP
 a| 
SSH
 a| 
L'ordinateur portable de service
 a| 
Appliances
 a| 
Permet d'accéder aux appliances StorageGRID en mode préconfiguration pour le support et le dépannage. Ce port n'est pas nécessaire pour être accessible entre des nœuds grid ou pendant les opérations normales.



 a| 
9091
 a| 
TCP
 a| 
HTTPS
 a| 
Service externe Grafana
 a| 
Nœuds d'administration
 a| 
Utilisés par les services Grafana externes pour sécuriser l'accès au service StorageGRID Prometheus.

*Remarque :* ce port n'est nécessaire que si l'accès Prometheus basé sur un certificat est activé.



 a| 
9443
 a| 
TCP
 a| 
HTTPS
 a| 
Navigateur
 a| 
Nœuds d'administration
 a| 
Facultatif. Utilisé par les navigateurs Web et les clients API de gestion pour accéder au Gestionnaire de locataires. Peut être utilisé pour séparer les communications Grid Manager et tenant Manager.



 a| 
18082
 a| 
TCP
 a| 
HTTPS
 a| 
Clients S3
 a| 
Nœuds de stockage
 a| 
Trafic externe lié à S3 vers les nœuds de stockage (HTTPS).



 a| 
18083
 a| 
TCP
 a| 
HTTPS
 a| 
Clients Swift
 a| 
Nœuds de stockage
 a| 
Trafic externe lié à Swift vers les nœuds de stockage (HTTPS).



 a| 
18084
 a| 
TCP
 a| 
HTTP
 a| 
Clients S3
 a| 
Nœuds de stockage
 a| 
Trafic externe lié à S3 vers les nœuds de stockage (HTTP).



 a| 
18085
 a| 
TCP
 a| 
HTTP
 a| 
Clients Swift
 a| 
Nœuds de stockage
 a| 
Trafic externe lié à Swift vers les nœuds de stockage (HTTP).

|===
.Informations associées
link:internal-grid-node-communications.html["Communications internes sur les nœuds de la grille"]

link:../rhel/index.html["Installez Red Hat Enterprise Linux ou CentOS"]

link:../ubuntu/index.html["Installez Ubuntu ou Debian"]

link:../vmware/index.html["Installez VMware"]

link:../sg100-1000/index.html["SG100 etamp ; appareils de services SG1000"]

link:../sg6000/index.html["Dispositifs de stockage SG6000"]

link:../sg5700/index.html["Appliances de stockage SG5700"]

link:../sg5600/index.html["Appliances de stockage SG5600"]
