---
permalink: vmware/planning-and-preparation.html 
sidebar: sidebar 
keywords:  
summary: Avant de déployer des nœuds grid et de configurer la grille de StorageGRID, vous devez connaître les étapes et les conditions requises pour terminer la procédure. 
---
= Planification et préparation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de déployer des nœuds grid et de configurer la grille de StorageGRID, vous devez connaître les étapes et les conditions requises pour terminer la procédure.

Les procédures de déploiement et de configuration de StorageGRID supposent que vous connaissez bien l'architecture et les fonctionnalités opérationnelles du système StorageGRID.

Vous pouvez déployer un ou plusieurs sites à la fois. Toutefois, tous les sites doivent respecter le minimum requis : disposer d'au moins trois nœuds de stockage.

Avant de démarrer la procédure de déploiement de nœuds et de configuration grid, vous devez :

* Planification du déploiement StorageGRID
* Installez, connectez et configurez tout le matériel requis, y compris les appliances StorageGRID, selon les spécifications.
+

NOTE: Des instructions d'installation et d'intégration spécifiques au matériel ne sont pas incluses dans la procédure d'installation de StorageGRID. Pour savoir comment installer des appliances StorageGRID, consultez les instructions d'installation et de maintenance de votre appareil.

* Découvrez les options réseau disponibles et la manière dont chaque option réseau doit être implémentée sur les nœuds de grid. Consultez les instructions de mise en réseau StorageGRID.
* Rassemblez toutes les informations de réseautage à l'avance. Sauf si vous utilisez DHCP, rassemblez les adresses IP à attribuer à chaque nœud de la grille ainsi que les adresses IP des serveurs DNS (Domain Name System) et NTP (Network Time Protocol) qui seront utilisés.
* Choisissez les outils de déploiement et de configuration que vous souhaitez utiliser.


.Informations associées
link:../network/index.html["Instructions réseau"]

link:../sg100-1000/index.html["SG100 etamp ; appareils de services SG1000"]

link:../sg6000/index.html["Dispositifs de stockage SG6000"]

link:../sg5700/index.html["Appliances de stockage SG5700"]

link:../sg5600/index.html["Appliances de stockage SG5600"]
