---
permalink: vmware/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: storagegrid, vmware, troubleshoot installation, troubleshooting installation 
summary: 'En cas de problème lors de l"installation de votre système StorageGRID, vous pouvez accéder aux fichiers journaux d"installation.' 
---
= Résolution des problèmes d'installation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En cas de problème lors de l'installation de votre système StorageGRID, vous pouvez accéder aux fichiers journaux d'installation.

Voici les principaux fichiers journaux d'installation dont le support technique peut avoir besoin pour résoudre les problèmes.

* `/var/local/log/install.log` (disponible sur tous les nœuds de la grille)
* `/var/local/log/gdu-server.log` (Trouvé sur le nœud d'administration principal)


Pour savoir comment accéder aux fichiers journaux, reportez-vous aux instructions de surveillance et de dépannage de StorageGRID. Pour obtenir de l'aide sur le dépannage des problèmes d'installation de l'appareil, consultez les instructions d'installation et de maintenance de vos appareils. Si vous avez besoin d'aide supplémentaire, contactez le support technique.

.Informations associées
link:../monitor/index.html["Moniteur et amp ; dépannage"]

link:../sg100-1000/index.html["SG100 etamp ; appareils de services SG1000"]

link:../sg6000/index.html["Dispositifs de stockage SG6000"]

link:../sg5700/index.html["Appliances de stockage SG5700"]

link:../sg5600/index.html["Appliances de stockage SG5600"]

https://["Support NetApp"^]
