---
permalink: vmware/virtual-machine-resource-reservation-requires-adjustment.html 
sidebar: sidebar 
keywords:  
summary: 'Les fichiers OVF incluent une réservation de ressources conçue pour garantir que chaque nœud de grille dispose de suffisamment de RAM et de CPU pour fonctionner efficacement. Si vous créez des machines virtuelles en déployant ces fichiers OVF sur VMware et que le nombre prédéfini de ressources n"est pas disponible, les machines virtuelles ne démarrent pas.' 
---
= La réservation de ressources de machine virtuelle nécessite un ajustement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les fichiers OVF incluent une réservation de ressources conçue pour garantir que chaque nœud de grille dispose de suffisamment de RAM et de CPU pour fonctionner efficacement. Si vous créez des machines virtuelles en déployant ces fichiers OVF sur VMware et que le nombre prédéfini de ressources n'est pas disponible, les machines virtuelles ne démarrent pas.

.Description de la tâche
Si vous êtes certain que l'hôte VM dispose de ressources suffisantes pour chaque nœud de la grille, ajustez manuellement les ressources allouées à chaque machine virtuelle, puis essayez de démarrer les machines virtuelles.

.Étapes
. Dans l'arborescence du client VMware vSphere Hypervisor, sélectionnez la machine virtuelle qui n'a pas démarré.
. Cliquez avec le bouton droit de la souris sur la machine virtuelle et sélectionnez *Modifier les paramètres*.
. Dans la fenêtre Propriétés des machines virtuelles, sélectionnez l'onglet *Ressources*.
. Ajustez les ressources allouées à la machine virtuelle :
+
.. Sélectionnez *CPU*, puis utilisez le curseur réservation pour régler la fréquence réservée à cette machine virtuelle.
.. Sélectionnez *mémoire*, puis utilisez le curseur réservation pour régler le Mo réservé pour cette machine virtuelle.


. Cliquez sur *OK*.
. Répétez cette procédure si nécessaire pour les autres machines virtuelles hébergées sur le même hôte VM.

