---
permalink: rhel/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: storagegrid, redhat, rhel, download installation files, downloading installation files 
summary: 'Vous devez télécharger l"archive d"installation de StorageGRID et extraire les fichiers requis.' 
---
= Téléchargement et extraction des fichiers d'installation de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez télécharger l'archive d'installation de StorageGRID et extraire les fichiers requis.

.Étapes
. Accédez à la page de téléchargements NetApp pour StorageGRID.
+
https://["Téléchargement NetApp : StorageGRID"^]

. Sélectionnez le bouton pour télécharger la dernière version ou sélectionnez une autre version dans le menu déroulant et sélectionnez *Go*.
. Connectez-vous avec le nom d'utilisateur et le mot de passe de votre compte NetApp.
. Si une instruction attention/MustRead s'affiche, lisez-la et cochez la case.
+
Après l'installation de la version StorageGRID, vous devez appliquer les correctifs requis. Pour plus d'informations, reportez-vous à la procédure de correctif dans les instructions de récupération et de maintenance.

. Lisez le contrat de licence de l'utilisateur final, cochez la case, puis sélectionnez *accepter et continuer*.
. Dans la colonne *installer StorageGRID*, sélectionnez le logiciel approprié.
+
Téléchargez le `.tgz` ou `.zip` fichier d'archivage pour votre plate-forme.

+
Les fichiers compressés contiennent les fichiers RPM et les scripts pour Red Hat Enterprise Linux ou CentOS.

+

NOTE: Utilisez le `.zip` Fichier si vous exécutez Windows sur l'ordinateur portable de service.

. Enregistrez et extrayez le fichier d'archive.
. Choisissez les fichiers dont vous avez besoin dans la liste suivante.
+
Les fichiers dont vous avez besoin dépendent de votre topologie de grille planifiée et de la manière dont vous allez déployer votre système StorageGRID.

+

NOTE: Les chemins répertoriés dans la table sont relatifs au répertoire de niveau supérieur installé par l'archive d'installation extraite.



[cols="1a,2a"]
|===
| Chemin d'accès et nom de fichier | Description 


| ./rpms/README  a| 
Fichier texte qui décrit tous les fichiers contenus dans le fichier de téléchargement StorageGRID.



| ./rpms/NLF000000.txt  a| 
Licence gratuite qui ne fournit aucun droit d'assistance pour le produit.



| ./rpms/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
Package RPM pour l'installation des images des nœuds StorageGRID sur vos hôtes RHEL ou CentOS.



| ./rpms/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
Package RPM pour l'installation du service hôte StorageGRID sur vos hôtes RHEL ou CentOS.



| Outil de script de déploiement | Description 


| ./rpms/configure-storagegrid.py  a| 
Script Python utilisé pour automatiser la configuration d'un système StorageGRID.



| ./rpms/configure-sga.py  a| 
Script Python utilisé pour automatiser la configuration des appliances StorageGRID.



| ./rpms/configure-storagegrid.sample.json  a| 
Exemple de fichier de configuration à utiliser avec le `configure-storagegrid.py` script.



| ./rpms/storagegrid-ssoauth.py  a| 
Exemple de script Python que vous pouvez utiliser pour vous connecter à l'API Grid Management lorsque l'authentification unique est activée.



| ./rpms/configure-storagegrid.blank.json  a| 
Un fichier de configuration vierge à utiliser avec le `configure-storagegrid.py` script.



| ./rpms/extras/ansible  a| 
Exemple de rôle et de manuel de vente Ansible pour la configuration des hôtes RHEL ou CentOS pour le déploiement de conteneurs StorageGRID. Vous pouvez personnaliser le rôle ou le PlayBook selon vos besoins.

|===
.Informations associées
link:../maintain/index.html["Maintenance et récupération"]
