---
permalink: admin/changing-your-password.html 
sidebar: sidebar 
keywords:  
summary: Si vous êtes un utilisateur local de Grid Manager, vous pouvez modifier votre propre mot de passe. 
---
= Modification de votre mot de passe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous êtes un utilisateur local de Grid Manager, vous pouvez modifier votre propre mot de passe.

.Ce dont vous avez besoin
Vous devez être connecté à Grid Manager à l'aide d'un navigateur pris en charge.

.Description de la tâche
Si vous vous connectez à StorageGRID en tant qu'utilisateur fédéré ou si l'authentification unique (SSO) est activée, vous ne pouvez pas modifier votre mot de passe dans Grid Manager. Vous devez plutôt modifier votre mot de passe dans le référentiel d'identité externe, par exemple Active Directory ou OpenLDAP.

.Étapes
. Dans l'en-tête de Grid Manager, sélectionnez *_votre nom_ > Modifier le mot de passe*.
. Saisissez votre mot de passe actuel.
. Saisissez un nouveau mot de passe.
+
Votre mot de passe doit contenir au moins 8 caractères et pas plus de 32 caractères. Les mots de passe sont sensibles à la casse.

. Saisissez à nouveau le nouveau mot de passe.
. Cliquez sur *Enregistrer*.

