---
permalink: admin/configuring-archive-node-connections-to-archival-storage.html 
sidebar: sidebar 
keywords:  
summary: 'Lorsque vous configurez un nœud d"archivage pour qu"il se connecte à une archive externe, vous devez sélectionner le type cible.' 
---
= Configuration des connexions du nœud d'archivage au stockage d'archivage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous configurez un nœud d'archivage pour qu'il se connecte à une archive externe, vous devez sélectionner le type cible.

Le système StorageGRID prend en charge l'archivage des données d'objet dans le cloud via une interface S3 ou sur bande via le logiciel médiateur Tivoli Storage Manager (TSM).


NOTE: Une fois le type de cible d'archivage configuré pour un nœud d'archivage, le type de cible ne peut pas être modifié.

* link:archiving-to-cloud-through-s3-api.html["Archivage dans le cloud via l'API S3"]
* link:archiving-to-tape-through-tsm-middleware.html["Archivage sur bande via le logiciel médiateur TSM"]
* link:configuring-archive-node-retrieve-settings.html["Configuration des paramètres de récupération du nœud d'archivage"]
* link:configuring-archive-node-replication.html["Configuration de la réplication du noeud d'archivage"]

