---
permalink: admin/creating-custom-notifications-for-migration-alarms.html 
sidebar: sidebar 
keywords:  
summary: 'StorageGRID peut envoyer des notifications d"alerte ou des notifications d"alarme \(système hérité\) à l"administrateur système responsable de la surveillance de la migration si certaines valeurs dépassent les seuils recommandés.' 
---
= Création de notifications personnalisées pour les alarmes de migration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID peut envoyer des notifications d'alerte ou des notifications d'alarme (système hérité) à l'administrateur système responsable de la surveillance de la migration si certaines valeurs dépassent les seuils recommandés.

.Ce dont vous avez besoin
* Vous devez être connecté à Grid Manager à l'aide d'un navigateur pris en charge.
* Vous devez disposer d'autorisations d'accès spécifiques.
* Vous devez avoir configuré les paramètres de messagerie pour les notifications d'alerte (ou d'alarme).


.Étapes
. Créez une règle d'alerte personnalisée ou une alarme personnalisée globale pour chaque metric Prometheus ou attribut StorageGRID que vous souhaitez surveiller pendant la migration des données.
+
Les alertes sont déclenchées en fonction des valeurs de mesure Prometheus. Les alarmes sont déclenchées en fonction des valeurs d'attribut. Pour plus d'informations, reportez-vous aux instructions de surveillance et de dépannage de StorageGRID.

. Désactivez la règle d'alerte personnalisée ou l'alarme personnalisée globale une fois la migration des données terminée.
+
Notez que les alarmes personnalisées globales remplacent les alarmes par défaut.



.Informations associées
link:../monitor/index.html["Moniteur et amp ; dépannage"]
