---
permalink: admin/guidelines-for-storagegrid-networks.html 
sidebar: sidebar 
keywords:  
summary: 'StorageGRID prend en charge jusqu"à trois interfaces réseau par nœud de grid, vous permettant de configurer le réseau pour chaque nœud de grid en fonction de vos besoins de sécurité et d"accès.' 
---
= Instructions pour les réseaux StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID prend en charge jusqu'à trois interfaces réseau par nœud de grid, vous permettant de configurer le réseau pour chaque nœud de grid en fonction de vos besoins de sécurité et d'accès.


NOTE: Pour modifier ou ajouter un réseau pour un nœud de grille, reportez-vous aux instructions de récupération et de maintenance. Pour plus d'informations sur la topologie du réseau, reportez-vous aux instructions de mise en réseau.



== Réseau Grid

Obligatoire. Le réseau Grid est utilisé pour l'ensemble du trafic StorageGRID interne. Il assure la connectivité entre tous les nœuds de la grille, sur tous les sites et sous-réseaux.



== Réseau d'administration

Facultatif. Le réseau d'administration est généralement utilisé pour l'administration et la maintenance du système. Il peut également être utilisé pour l'accès au protocole client. Le réseau Admin est généralement un réseau privé et n'a pas besoin d'être routable entre les sites.



== Réseau client

Facultatif. Le réseau client est un réseau ouvert généralement utilisé pour fournir l'accès aux applications client S3 et Swift, de sorte que le réseau Grid puisse être isolé et sécurisé. Le réseau client peut communiquer avec tout sous-réseau accessible via la passerelle locale.



== Directives

* Chaque nœud de grid StorageGRID nécessite une interface réseau dédiée, une adresse IP, un masque de sous-réseau et une passerelle pour chaque réseau auquel il est attribué.
* Un nœud de grid ne peut pas avoir plusieurs interfaces sur un réseau.
* Une passerelle unique, par réseau et par nœud grid est prise en charge et doit être sur le même sous-réseau que le nœud. Vous pouvez implémenter un routage plus complexe dans la passerelle, si nécessaire.
* Sur chaque nœud, chaque réseau est mappé à une interface réseau spécifique.
+
[cols="1a,1a"]
|===
| Le réseau | Nom de l'interface 


 a| 
Grille
 a| 
eth0



 a| 
Administrateur (en option)
 a| 
eth1



 a| 
Client (facultatif)
 a| 
eth2

|===
* Si le nœud est connecté à une appliance StorageGRID, des ports spécifiques sont utilisés pour chaque réseau. Pour plus de détails, reportez-vous aux instructions d'installation de votre appareil.
* La route par défaut est générée automatiquement, par nœud. Si eth2 est activé, 0.0.0.0/0 utilise le réseau client sur eth2. Si eth2 n'est pas activé, alors 0.0.0.0/0 utilise le réseau Grid sur eth0.
* Le réseau client n'est opérationnel qu'après que le nœud de la grille ait rejoint la grille
* Le réseau Admin peut être configuré pendant le déploiement du nœud grid pour permettre l'accès à l'interface utilisateur d'installation avant que la grille soit entièrement installée.


.Informations associées
link:../maintain/index.html["Maintenance et récupération"]

link:../network/index.html["Instructions réseau"]
