---
permalink: admin/how-ha-groups-are-used.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez utiliser les groupes haute disponibilité \(HA\) pour plusieurs raisons.' 
---
= Mode d'utilisation des groupes haute disponibilité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser les groupes haute disponibilité (HA) pour plusieurs raisons.

* Un groupe haute disponibilité peut fournir des connexions administratives hautement disponibles vers le Grid Manager ou le tenant Manager.
* Un groupe haute disponibilité peut fournir des connexions de données extrêmement disponibles pour les clients S3 et Swift.
* Un groupe haute disponibilité ne contenant qu'une interface vous permet de fournir de nombreuses adresses VIP et de définir explicitement des adresses IPv6.


Un groupe haute disponibilité peut assurer la haute disponibilité uniquement si tous les nœuds du groupe fournissent les mêmes services. Lorsque vous créez un groupe haute disponibilité, ajoutez des interfaces à partir des types de nœuds qui fournissent les services requis.

* *Nœuds d'administration* : incluez le service Load Balancer et activez l'accès au Grid Manager ou au Gestionnaire de locataires.
* *Gateway Nodes* : inclut le service Load Balancer et le service CLB (obsolète).


[cols="1a,1a"]
|===
| Objectif du groupe haute disponibilité | Ajout de nœuds de ce type au groupe haute disponibilité 


 a| 
Accès à Grid Manager
 a| 
* Nœud d'administration principal (*maître préféré*)
* Nœuds d'administration non primaires


*Remarque :* le noeud d'administration principal doit être le maître préféré. Certaines procédures de maintenance peuvent uniquement être effectuées depuis le nœud d'administration principal.



 a| 
Accès au Gestionnaire de locataires uniquement
 a| 
* Nœuds d'administration primaires ou non primaires




 a| 
Accès client S3 ou Swift -- Service Load Balancer
 a| 
* Nœuds d'administration
* Nœuds de passerelle




 a| 
Accès client S3 ou Swift -- service CLB

*Note:* le service CLB est obsolète.
 a| 
* Nœuds de passerelle


|===


== Restrictions liées à l'utilisation de groupes haute disponibilité avec Grid Manager ou tenant Manager

L'échec des services de Grid Manager ou de tenant Manager n'entraîne pas de basculement au sein du groupe haute disponibilité.

Si vous êtes connecté au Grid Manager ou au tenant Manager lors du basculement, vous êtes déconnecté et vous devez vous reconnecter pour reprendre votre tâche.

Certaines procédures de maintenance ne peuvent pas être effectuées lorsque le nœud d'administration principal n'est pas disponible. Pendant le basculement, vous pouvez utiliser le Gestionnaire de grille pour surveiller votre système StorageGRID.



== Limites de l'utilisation de groupes HA avec le service CLB

La défaillance du service CLB ne déclenche pas de basculement au sein du groupe HA.


NOTE: Le service CLB est obsolète.
