---
permalink: admin/kms-adding.html 
sidebar: sidebar 
keywords:  
summary: 'L"assistant de serveur de gestion des clés StorageGRID vous permet d"ajouter chaque cluster KMS ou KMS.' 
---
= Ajout d'un serveur de gestion des clés (KMS)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'assistant de serveur de gestion des clés StorageGRID vous permet d'ajouter chaque cluster KMS ou KMS.

.Ce dont vous avez besoin
* Vous devez avoir consulté le link:kms-considerations-and-requirements.html["considérations et conditions requises pour l'utilisation d'un serveur de gestion des clés"].
* Vous devez avoir link:kms-configuring-storagegrid-as-client.html["Configuration de StorageGRID en tant que client dans le KMS"], Et vous devez disposer des informations requises pour chaque cluster KMS ou KMS
* Vous devez disposer de l'autorisation accès racine.
* Vous devez être connecté à Grid Manager à l'aide d'un navigateur pris en charge.


.Description de la tâche
Si possible, configurez tous les serveurs de gestion de clés spécifiques au site avant de configurer un KMS par défaut qui s'applique à tous les sites non gérés par un autre KMS. Si vous créez d'abord le KMS par défaut, toutes les appliances chiffrées par nœud dans le grid seront chiffrées par le KMS par défaut. Si vous souhaitez créer ultérieurement un KMS spécifique au site, vous devez d'abord copier la version actuelle de la clé de chiffrement à partir du KMS par défaut vers le nouveau KMS.

link:kms-considerations-for-changing-for-site.html["Considérations relatives à la modification du KMS pour un site"]

.Étapes
. link:kms-adding-enter-kms-details.html["Étape 1 : saisissez les détails du KMS"]
. link:kms-adding-upload-server-certificate.html["Étape 2 : télécharger le certificat du serveur"]
. link:kms-adding-upload-client-certificates.html["Étape 3 : télécharger des certificats client"]

