---
permalink: admin/managing-storage-nodes.html 
sidebar: sidebar 
keywords:  
summary: 'Des nœuds de stockage fournissent de la capacité de stockage sur disque et des services. La gestion des nœuds de stockage consiste à contrôler la quantité d"espace utilisable sur chaque nœud, à l"aide des paramètres de filigrane et à appliquer les paramètres de configuration du nœud de stockage.' 
---
= Gestion des nœuds de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Des nœuds de stockage fournissent de la capacité de stockage sur disque et des services. La gestion des nœuds de stockage consiste à contrôler la quantité d'espace utilisable sur chaque nœud, à l'aide des paramètres de filigrane et à appliquer les paramètres de configuration du nœud de stockage.

* link:what-storage-node-is.html["Qu'est-ce qu'un noeud de stockage"]
* link:managing-storage-options.html["Gestion des options de stockage"]
* link:managing-object-metadata-storage.html["Gestion du stockage des métadonnées d'objet"]
* link:configuring-global-settings-for-stored-objects.html["Configuration des paramètres globaux des objets stockés"]
* link:storage-node-configuration-settings.html["Paramètres de configuration du nœud de stockage"]
* link:managing-full-storage-nodes.html["Gestion des nœuds de stockage complets"]

