---
permalink: admin/restoring-default-server-certificates-for-grid-manager-tenant-manager.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez revenir à l"utilisation des certificats de serveur par défaut pour le Grid Manager et le tenant Manager.' 
---
= Restauration des certificats de serveur par défaut pour le Grid Manager et le tenant Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez revenir à l'utilisation des certificats de serveur par défaut pour le Grid Manager et le tenant Manager.

.Étapes
. Sélectionnez *Configuration* > *Paramètres réseau* > *certificats serveur*.
. Dans la section gérer le certificat du serveur d'interface, cliquez sur *utiliser les certificats par défaut*.
. Cliquez sur *OK* dans la boîte de dialogue de confirmation.
+
Lorsque vous restaurez les certificats de serveur par défaut, les fichiers de certificat de serveur personnalisés que vous avez configurés sont supprimés et ne peuvent pas être récupérés du système. Les certificats de serveur par défaut sont utilisés pour toutes les nouvelles connexions client suivantes.

. Actualisez la page pour vous assurer que le navigateur Web est mis à jour.

