---
permalink: admin/setting-archive-node-to-read-only-if-tsm-middleware-reaches-capacity.html 
sidebar: sidebar 
keywords:  
summary: 'Si le serveur middleware TSM cible atteint sa capacité, le nœud d"archivage peut être optimisé pour effectuer uniquement des récupérations.' 
---
= Configuration du nœud d'archivage en lecture seule si le middleware TSM atteint sa capacité maximale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si le serveur middleware TSM cible atteint sa capacité, le nœud d'archivage peut être optimisé pour effectuer uniquement des récupérations.

.Ce dont vous avez besoin
* Vous devez être connecté à Grid Manager à l'aide d'un navigateur pris en charge.
* Vous devez disposer d'autorisations d'accès spécifiques.


.Étapes
. Sélectionnez *support* > *Outils* > *topologie de grille*.
. Sélectionnez *_Archive Node_* > *ARC* > *cible*.
. Sélectionnez *Configuration* > *main*.
. Modifiez le nombre maximal de sessions de récupération pour qu'il soit identique au nombre de sessions simultanées répertoriées dans nombre de sessions.
. Définissez le nombre maximum de sessions de stockage sur 0.
+

NOTE: Il n'est pas nécessaire de modifier le nombre maximal de sessions de stockage sur 0 si le nœud d'archivage est en lecture seule. Les sessions de magasin ne seront pas créées.

. Cliquez sur *appliquer les modifications*.

