---
permalink: admin/updating-storagegrid-license-information.html 
sidebar: sidebar 
keywords:  
summary: Vous devez mettre à jour les informations de licence de votre système StorageGRID à tout moment que les conditions de votre modification de licence changent. Par exemple, vous devez mettre à jour les informations de licence si vous achetez de la capacité de stockage supplémentaire pour votre grid. 
---
= Mise à jour des informations de licence StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez mettre à jour les informations de licence de votre système StorageGRID à tout moment que les conditions de votre modification de licence changent. Par exemple, vous devez mettre à jour les informations de licence si vous achetez de la capacité de stockage supplémentaire pour votre grid.

.Ce dont vous avez besoin
* Vous devez disposer d'un nouveau fichier de licence pour appliquer votre système StorageGRID.
* Vous devez disposer d'autorisations d'accès spécifiques.
* Vous devez disposer de la phrase secrète pour le provisionnement.


.Étapes
. Sélectionnez *Maintenance* > *système* > *Licence*.
. Saisissez le mot de passe de provisionnement de votre système StorageGRID dans la zone de texte *phrase de passe de provisionnement*.
. Cliquez sur *Parcourir*.
. Dans la boîte de dialogue Ouvrir, localisez et sélectionnez le nouveau fichier de licence (`.txt`), puis cliquez sur *Ouvrir*.
+
Le nouveau fichier de licence est validé et affiché.

. Cliquez sur *Enregistrer*.

