---
permalink: admin/using-grid-management-api.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez effectuer des tâches de gestion du système à l"aide de l"API REST Grid Management plutôt que de l"interface utilisateur Grid Manager. Par exemple, vous pouvez utiliser l"API pour automatiser les opérations ou créer plusieurs entités plus rapidement (par exemple, les utilisateurs).' 
---
= Via l'API de gestion du grid
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer des tâches de gestion du système à l'aide de l'API REST Grid Management plutôt que de l'interface utilisateur Grid Manager. Par exemple, vous pouvez utiliser l'API pour automatiser les opérations ou créer plusieurs entités plus rapidement (par exemple, les utilisateurs).

L'API Grid Management utilise la plateforme d'API open source swagger. Swagger fournit une interface utilisateur intuitive qui permet aux développeurs et aux non-développeurs d'effectuer des opérations en temps réel dans StorageGRID avec l'API.



== Ressources générales

L'API de gestion du grid fournit les ressources de premier niveau suivantes :

* `/grid`: L'accès est limité aux utilisateurs de Grid Manager et est basé sur les autorisations de groupe configurées.
* `/org`: L'accès est limité aux utilisateurs qui appartiennent à un groupe LDAP local ou fédéré pour un compte locataire. Pour plus de détails, reportez-vous aux informations sur l'utilisation des comptes de tenant.
* `/private`: L'accès est limité aux utilisateurs de Grid Manager et est basé sur les autorisations de groupe configurées. Ces API sont destinées à un usage interne uniquement et ne sont pas documentées publiquement. Ces API sont également susceptibles d'être modifiées sans préavis.


.Informations associées
link:../tenant/index.html["Utilisez un compte de locataire"]

https://prometheus.io/docs/querying/basics/["Prometheus : notions de base sur les requêtes"^]
