---
permalink: s3/custom-operations-on-buckets.html 
sidebar: sidebar 
keywords: operations, buckets, custom, custom operations on buckets 
summary: 'Le système StorageGRID prend en charge les opérations de compartiment personnalisées, ajoutées à l"API REST S3 et propres au système.' 
---
= Opérations personnalisées dans les compartiments
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le système StorageGRID prend en charge les opérations de compartiment personnalisées, ajoutées à l'API REST S3 et propres au système.

Le tableau suivant répertorie les opérations de compartiment personnalisées prises en charge par StorageGRID.

|===
| Fonctionnement | Description | Pour en savoir plus 


 a| 
OPTIMISEZ la cohérence des compartiments
 a| 
Renvoie le niveau de cohérence appliqué à un compartiment spécifique.
 a| 
link:storagegrid-s3-rest-api-operations.html["DEMANDE de cohérence des compartiments"]



 a| 
PRÉSERVER la cohérence du godet
 a| 
Définit le niveau de cohérence appliqué à un compartiment spécifique.
 a| 
link:storagegrid-s3-rest-api-operations.html["PUT Bucket Consistency demandée"]



 a| 
HEURE du dernier accès au compartiment
 a| 
Indique si les mises à jour de l'heure du dernier accès sont activées ou désactivées pour un compartiment spécifique.
 a| 
link:storagegrid-s3-rest-api-operations.html["DEMANDE DE dernier accès au compartiment"]



 a| 
METTRE l'heure du dernier accès au compartiment
 a| 
Permet d'activer ou de désactiver les mises à jour de l'heure du dernier accès pour un compartiment spécifique.
 a| 
link:storagegrid-s3-rest-api-operations.html["DEMANDE de temps de dernier accès au compartiment"]



 a| 
SUPPRIMEZ la configuration de notification des métadonnées de compartiment
 a| 
Supprime le XML de configuration de notification de métadonnées associé à un compartiment spécifique.
 a| 
link:storagegrid-s3-rest-api-operations.html["SUPPRIME la demande de configuration de notification des métadonnées de compartiment"]



 a| 
CONFIGURATION DES notifications de métadonnées de compartiment
 a| 
Renvoie le XML de configuration de notification de métadonnées associé à un compartiment spécifique.
 a| 
link:storagegrid-s3-rest-api-operations.html["LIRE la demande de configuration de notification des métadonnées de compartiment"]



 a| 
CONFIGURATION de notification des métadonnées de compartiment
 a| 
Configure le service de notification des métadonnées pour un compartiment.
 a| 
link:storagegrid-s3-rest-api-operations.html["PUT Bucket metadata notification configuration"]



 a| 
METTEZ les modifications du godet à des fins de conformité
 a| 
Obsolète et non pris en charge : vous ne pouvez plus créer de compartiments avec conformité activée.
 a| 
link:storagegrid-s3-rest-api-operations.html["Obsolète : METTEZ les modifications de la demande de compartiment à des fins de conformité"]



 a| 
ASSUREZ la conformité aux compartiments
 a| 
Obsolète mais pris en charge : renvoie les paramètres de conformité actuellement en vigueur pour un compartiment compatible existant.
 a| 
link:storagegrid-s3-rest-api-operations.html["Obsolète : RÉCUPÉRER la demande de conformité du compartiment"]



 a| 
METTEZ le godet en conformité
 a| 
Obsolète mais pris en charge : permet de modifier les paramètres de conformité d'un compartiment compatible existant.
 a| 
link:storagegrid-s3-rest-api-operations.html["Obsolète : PUT Bucket Compliance request"]

|===
.Informations associées
link:s3-operations-tracked-in-audit-logs.html["Opérations S3 suivies dans les journaux d'audit"]
