---
permalink: s3/operations-on-objects.html 
sidebar: sidebar 
keywords: bucket, buckets, operations on buckets 
summary: 'Cette section décrit la manière dont le système StorageGRID implémente les opérations de l"API REST S3 pour les objets.' 
---
= Opérations sur les objets
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette section décrit la manière dont le système StorageGRID implémente les opérations de l'API REST S3 pour les objets.

* link:using-s3-object-lock.html["Utilisation du verrouillage d'objet S3"]
* link:using-server-side-encryption.html["Utilisation du chiffrement côté serveur"]
* link:get-object.html["OBTENIR l'objet"]
* link:head-object.html["Objet TÊTE"]
* link:post-object-restore.html["Restauration POST-objet"]
* link:put-object.html["PLACER l'objet"]
* link:put-object-copy.html["PLACER l'objet - Copier"]


Les conditions suivantes s'appliquent à toutes les opérations d'objet :

* Les contrôles de cohérence StorageGRID sont pris en charge par toutes les opérations sur les objets, à l'exception de ce qui suit :
+
** OBTENIR l'ACL d'objet
** `OPTIONS /`
** METTRE l'objet en attente légale
** CONSERVATION des objets


* Les demandes contradictoires des clients, telles que deux clients qui écrivent sur la même clé, sont résolues sur la base des « derniers-victoires ». Le moment de l'évaluation « derniers-victoires » est basé sur le moment où le système StorageGRID remplit une demande donnée et non sur le moment où les clients S3 commencent une opération.
* Tous les objets d'un compartiment StorageGRID sont détenus par le propriétaire du compartiment, y compris les objets créés par un utilisateur anonyme ou par un autre compte.
* Les objets de données ingérées sur le système StorageGRID via Swift ne sont pas accessibles via S3.


Le tableau ci-dessous décrit la manière dont StorageGRID implémente les opérations sur les objets de l'API REST S3.

|===
| Fonctionnement | Mise en place 


 a| 
SUPPRIMER l'objet
 a| 
Authentification multifacteur (MFA) et en-tête de réponse `x-amz-mfa` ne sont pas pris en charge.

Lors du traitement d'une requête DE SUPPRESSION d'objet, StorageGRID tente de supprimer immédiatement toutes les copies de l'objet des emplacements stockés. En cas de succès, StorageGRID renvoie immédiatement une réponse au client. Si toutes les copies ne peuvent pas être supprimées dans les 30 secondes (par exemple, si un emplacement est temporairement indisponible), StorageGRID met les copies en file d'attente pour suppression, puis indique que le client a réussi à les supprimer.

*Gestion des versions*

Pour supprimer une version spécifique, le demandeur doit être le propriétaire du compartiment et utiliser le `versionId` sous-ressource. L'utilisation de cette sous-ressource supprime définitivement la version. Si le `versionId` correspond à un marqueur de suppression, l'en-tête de réponse `x-amz-delete-marker` est renvoyé à `true`.

* Si un objet est supprimé sans l' `versionId` sous-ressource sur un compartiment activé pour la version, il génère un marqueur de suppression. Le `versionId` pour le marqueur de suppression, est renvoyé à l'aide du `x-amz-version-id` en-tête de réponse, et le `x-amz-delete-marker` l'en-tête de réponse est renvoyé à `true`.
* Si un objet est supprimé sans l' `versionId` sous-ressource sur un compartiment suspendu de version, elle entraîne la suppression permanente d'une version existante 'null' ou d'un marqueur de suppression 'null' et la génération d'un nouveau marqueur de suppression 'null'. Le `x-amz-delete-marker` l'en-tête de réponse est renvoyé à `true`.


*Remarque* : dans certains cas, plusieurs marqueurs de suppression peuvent exister pour un objet.



 a| 
SUPPRIMER plusieurs objets
 a| 
Authentification multifacteur (MFA) et en-tête de réponse `x-amz-mfa` ne sont pas pris en charge.

Plusieurs objets peuvent être supprimés dans le même message de demande.



 a| 
SUPPRIMER le balisage d'objets
 a| 
Utilise le `tagging` sous-ressource pour supprimer toutes les balises d'un objet. Mise en œuvre avec tout le comportement de l'API REST Amazon S3.

*Gestion des versions*

Si le `versionId` le paramètre query n'est pas spécifié dans la demande. l'opération supprime toutes les balises de la version la plus récente de l'objet dans un compartiment versionné. Si la version actuelle de l'objet est un marqueur de suppression, un état "methodNotAldue" est renvoyé avec l' `x-amz-delete-marker` réponse en-tête réglée sur `true`.



 a| 
OBTENIR l'objet
 a| 
link:get-object.html["OBTENIR l'objet"]



 a| 
OBTENIR l'ACL d'objet
 a| 
Si les informations d'identification d'accès nécessaires sont fournies pour le compte, l'opération renvoie une réponse positive ainsi que l'ID, le DisplayName et l'autorisation du propriétaire de l'objet, ce qui indique que le propriétaire dispose d'un accès complet à l'objet.



 a| 
OBTENIR la mise en attente légale de l'objet
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["Utilisation du verrouillage d'objet S3"]



 a| 
OBTENIR la conservation des objets
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["Utilisation du verrouillage d'objet S3"]



 a| 
OBTENIR le balisage d'objets
 a| 
Utilise le `tagging` sous-ressource pour renvoyer toutes les balises d'un objet. Mise en œuvre avec tout le comportement de l'API REST Amazon S3

*Gestion des versions*

Si le `versionId` le paramètre query n'est pas spécifié dans la demande, l'opération renvoie toutes les balises de la version la plus récente de l'objet dans un compartiment versionné. Si la version actuelle de l'objet est un marqueur de suppression, un état "methodNotAldue" est renvoyé avec l' `x-amz-delete-marker` réponse en-tête réglée sur `true`.



 a| 
Objet TÊTE
 a| 
link:head-object.html["Objet TÊTE"]



 a| 
Restauration POST-objet
 a| 
link:post-object-restore.html["Restauration POST-objet"]



 a| 
PLACER l'objet
 a| 
link:put-object.html["PLACER l'objet"]



 a| 
PLACER l'objet - Copier
 a| 
link:put-object-copy.html["PLACER l'objet - Copier"]



 a| 
METTRE l'objet en attente légale
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["Utilisation du verrouillage d'objet S3"]



 a| 
CONSERVATION des objets
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["Utilisation du verrouillage d'objet S3"]



 a| 
PUT Object tagging
 a| 
Utilise le `tagging` sous-ressource pour ajouter un ensemble de balises à un objet existant. Mise en œuvre avec tout le comportement de l'API REST Amazon S3

*Mises à jour de balises et comportement d'entrée*

Lorsque vous utilisez PUT Object tagging pour mettre à jour les balises d'un objet, StorageGRID ne réingérer pas l'objet. Cela signifie que l'option de comportement d'ingestion spécifiée dans la règle ILM correspondante n'est pas utilisée. Tout changement au placement d'objet déclenché par la mise à jour est apporté lors de l'évaluation de ILM par des processus ILM en arrière-plan normaux.

Cela signifie que si la règle ILM utilise l'option stricte pour le comportement d'ingestion, aucune action n'est effectuée si les placements d'objet requis ne peuvent pas être effectués (par exemple, car un nouvel emplacement requis n'est pas disponible). L'objet mis à jour conserve son emplacement actuel jusqu'à ce que le placement requis soit possible.

*Résolution des conflits*

Les demandes contradictoires des clients, telles que deux clients qui écrivent sur la même clé, sont résolues sur la base des « derniers-victoires ». Le moment de l'évaluation « derniers-victoires » est basé sur le moment où le système StorageGRID remplit une demande donnée et non sur le moment où les clients S3 commencent une opération.

*Gestion des versions*

Si le `versionId` le paramètre de requête n'est pas spécifié dans la requête, l'opération ajoute des balises à la version la plus récente de l'objet dans un compartiment versionné. Si la version actuelle de l'objet est un marqueur de suppression, un état "methodNotAldue" est renvoyé avec l' `x-amz-delete-marker` réponse en-tête réglée sur `true`.

|===
.Informations associées
link:consistency-controls.html["Contrôles de cohérence"]

link:s3-operations-tracked-in-audit-logs.html["Opérations S3 suivies dans les journaux d'audit"]
