---
permalink: monitor/generating-text-reports.html 
sidebar: sidebar 
keywords: reports, text 
summary: 'Les rapports texte affichent une représentation textuelle des valeurs de données d"attribut traitées par le service NMS. Vous pouvez générer des rapports sur un site de data Center, un nœud grid, un composant ou un service.' 
---
= Génération de rapports texte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les rapports texte affichent une représentation textuelle des valeurs de données d'attribut traitées par le service NMS. Vous pouvez générer des rapports sur un site de data Center, un nœud grid, un composant ou un service.

.Ce dont vous avez besoin
* Vous devez être connecté à Grid Manager à l'aide d'un navigateur pris en charge.
* Vous devez disposer d'autorisations d'accès spécifiques.


.Description de la tâche
Pour les données d'attribut qui devraient changer en permanence, ces données d'attribut sont échantillonnées par le service NMS (à la source) à intervalles réguliers. Pour les données d'attribut qui changent rarement (par exemple, les données en fonction d'événements tels que les changements d'état ou d'état), une valeur d'attribut est envoyée au service NMS lorsque la valeur change.

Le type de rapport affiché dépend de la période configurée. Par défaut, les rapports de texte agrégés sont générés pour les périodes de plus d'une semaine.

Le texte gris indique que le service a été désactivé administrativement au cours de l'échantillonnage. Le texte bleu indique que le service était dans un état inconnu.

.Étapes
. Sélectionnez *support* > *Outils* > *topologie de grille*.
. Sélectionnez *_grid node_* > *_component ou service_* > *Reports* > *Text*.
. Sélectionnez l'attribut à rapporter dans la liste déroulante *attribut*.
. Sélectionnez le nombre de résultats par page dans la liste déroulante *Résultats par page*.
. Pour arrondir les valeurs à un maximum de trois décimales (par exemple, pour les attributs signalés sous forme de pourcentages), décochez la case *données brutes*.
. Sélectionnez la période à laquelle effectuer le rapport dans la liste déroulante *requête rapide*.
+
Sélectionnez l'option requête personnalisée pour sélectionner une plage de temps spécifique.

+
Le rapport apparaît après quelques instants. Prévoir plusieurs minutes pour la totalisation de longues plages de temps.

. Si vous avez sélectionné requête personnalisée, vous devez personnaliser la période de rapport en entrant *Date de début* et *Date de fin*.
+
Utiliser le format `YYYY/MM/DDHH:MM:SS` en heure locale. Des zéros non significatifs sont nécessaires pour correspondre au format. Par exemple, la validation a échoué dans 2017/4/6 7:30:00. Le format correct est: 2017/04/06 07:30:00.

. Cliquez sur *mettre à jour*.
+
Un rapport texte est généré au bout de quelques instants. Prévoir plusieurs minutes pour la totalisation de longues plages de temps. En fonction de la durée définie pour la requête, un rapport texte brut ou texte agrégé s'affiche.

. Si vous souhaitez imprimer le rapport, cliquez avec le bouton droit de la souris et sélectionnez *Imprimer*, puis modifiez les paramètres de l'imprimante requis et cliquez sur *Imprimer*.

