---
permalink: monitor/generating-charts.html 
sidebar: sidebar 
keywords: charts, generating 
summary: 'Les graphiques affichent une représentation graphique des valeurs de données d"attribut. Vous pouvez générer des rapports sur un site de data Center, un nœud grid, un composant ou un service.' 
---
= Génération de graphiques
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les graphiques affichent une représentation graphique des valeurs de données d'attribut. Vous pouvez générer des rapports sur un site de data Center, un nœud grid, un composant ou un service.

.Ce dont vous avez besoin
* Vous devez être connecté à Grid Manager à l'aide d'un navigateur pris en charge.
* Vous devez disposer d'autorisations d'accès spécifiques.


.Étapes
. Sélectionnez *support* > *Outils* > *topologie de grille*.
. Sélectionnez *_grid node_* > *_component ou service_* > *Rapports* > *diagrammes*.
. Sélectionnez l'attribut à rapporter dans la liste déroulante *attribut*.
. Pour forcer l'axe y à commencer à zéro, décochez la case *mise à l'échelle verticale*.
. Pour afficher les valeurs avec précision totale, cochez la case *données brutes* ou arrondissez les valeurs à un maximum de trois décimales (par exemple, pour les attributs signalés sous forme de pourcentages), décochez la case *données brutes*.
. Sélectionnez la période à laquelle effectuer le rapport dans la liste déroulante *requête rapide*.
+
Sélectionnez l'option requête personnalisée pour sélectionner une plage de temps spécifique.

+
Le graphique apparaît après quelques instants. Prévoir plusieurs minutes pour la totalisation de longues plages de temps.

. Si vous avez sélectionné requête personnalisée, personnalisez la période de temps du graphique en saisissant *Date de début* et *Date de fin*.
+
Utiliser le format `_YYYY/MM/DDHH:MM:SS_` en heure locale. Des zéros non significatifs sont nécessaires pour correspondre au format. Par exemple, la validation a échoué dans 2017/4/6 7:30:00. Le format correct est: 2017/04/06 07:30:00.

. Cliquez sur *mettre à jour*.
+
Un graphique est généré après quelques instants. Prévoir plusieurs minutes pour la totalisation de longues plages de temps. En fonction de la durée définie pour la requête, un rapport texte brut ou texte agrégé s'affiche.

. Si vous souhaitez imprimer le graphique, cliquez avec le bouton droit de la souris et sélectionnez *Imprimer*, puis modifiez les paramètres de l'imprimante requis et cliquez sur *Imprimer*.

