---
permalink: monitor/information-you-should-monitor-regularly.html 
sidebar: sidebar 
keywords: monitor, monitoring, StorageGRID, 
summary: 'StorageGRID est un système de stockage distribué, tolérant aux pannes et conçu pour continuer à fonctionner même en cas d"erreur, ou lorsque des nœuds ou des sites sont indisponibles. Vous devez surveiller de manière proactive l"état du système, les charges de travail et les statistiques d"utilisation afin de pouvoir prendre des mesures pour résoudre les problèmes potentiels avant qu"ils n"affectent l"efficacité ou la disponibilité du réseau.' 
---
= Informations à surveiller régulièrement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID est un système de stockage distribué, tolérant aux pannes et conçu pour continuer à fonctionner même en cas d'erreur, ou lorsque des nœuds ou des sites sont indisponibles. Vous devez surveiller de manière proactive l'état du système, les workloads et les statistiques d'utilisation afin de pouvoir prendre les mesures nécessaires pour résoudre les problèmes potentiels avant qu'ils n'affectent l'efficacité ou la disponibilité du réseau.

Un système occupé génère de grandes quantités d'informations. Cette section fournit des conseils sur les informations les plus importantes à surveiller de façon continue. Cette section contient les sous-sections suivantes :

* link:monitoring-system-health.html["Surveillance de l'état du système"]
* link:monitoring-storage-capacity.html["Contrôle de la capacité de stockage"]
* link:monitoring-information-lifecycle-management.html["Contrôle de la gestion du cycle de vie des informations"]
* link:monitoring-performance-networking-and-system-resources.html["Surveillance des performances, de la mise en réseau et des ressources système"]
* link:monitoring-tenant-activity.html["Contrôle de l'activité des locataires"]
* link:monitoring-archival-capacity.html["Contrôle de la capacité d'archivage"]
* link:monitoring-load-balancing-operations.html["Surveillance des opérations d'équilibrage des charges"]
* link:applying-hotfixes-or-upgrading-software-if-necessary.html["Application de correctifs ou mise à niveau des logiciels si nécessaire"]


|===
| Quoi surveiller | Fréquence 


 a| 
Les données d'état du système qui s'affichent sur le tableau de bord de Grid Manager si quelque chose a changé par rapport à la veille.
 a| 
Tous les jours



 a| 
Vitesse de consommation de la capacité des objets et des métadonnées du nœud de stockage
 a| 
Hebdomadaire



 a| 
Opérations de gestion du cycle de vie des informations
 a| 
Hebdomadaire



 a| 
Performances, mise en réseau et ressources système :

* Latence des requêtes
* Connectivité et réseau
* Ressources au niveau des nœuds

 a| 
Hebdomadaire



 a| 
Activité des locataires
 a| 
Hebdomadaire



 a| 
Capacité du système de stockage d'archives externe
 a| 
Hebdomadaire



 a| 
Opérations d'équilibrage de la charge
 a| 
Après la configuration initiale et après toute modification de la configuration



 a| 
Disponibilité des correctifs logiciels et des mises à niveau logicielles
 a| 
Tous les mois

|===