---
permalink: monitor/monitoring-storage-capacity.html 
sidebar: sidebar 
keywords:  
summary: 'Vous devez contrôler l"espace total disponible sur les nœuds de stockage pour vérifier que l"espace de stockage disponible sur le système StorageGRID n"est pas insuffisant pour les objets ou les métadonnées d"objet.' 
---
= Contrôle de la capacité de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez contrôler l'espace total disponible sur les nœuds de stockage pour vérifier que l'espace de stockage disponible sur le système StorageGRID n'est pas insuffisant pour les objets ou les métadonnées d'objet.

StorageGRID stocke séparément les données d'objet et les métadonnées d'objet. Il réserve un espace spécifique pour une base de données Cassandra distribuée qui contient les métadonnées d'objet. Surveiller la quantité totale d'espace consommée pour les objets et les métadonnées d'objet, ainsi que les tendances en matière de quantité d'espace consommée pour chaque. Vous pourrez ainsi planifier l'ajout de nœuds et éviter toute panne de service.

Vous pouvez afficher les informations de capacité de stockage pour l'ensemble de la grille, pour chaque site et pour chaque nœud de stockage de votre système StorageGRID.

.Informations associées
link:viewing-storage-tab.html["Affichage de l'onglet stockage"]
