---
permalink: maintain/checking-storage-state-after-recovering-storage-node-system-drive.html 
sidebar: sidebar 
keywords: storagegrid, storage node recovery, system drive, storage state 
summary: 'Après avoir restauré le lecteur système d"un noeud de stockage, vous devez vérifier que l"état souhaité du noeud de stockage est défini sur en ligne et vous assurer que l"état est en ligne par défaut à chaque redémarrage du serveur de noeud de stockage.' 
---
= Vérification de l'état du stockage après la récupération d'un lecteur système de nœud de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir restauré le lecteur système d'un noeud de stockage, vous devez vérifier que l'état souhaité du noeud de stockage est défini sur en ligne et vous assurer que l'état est en ligne par défaut à chaque redémarrage du serveur de noeud de stockage.

.Ce dont vous avez besoin
* Vous devez être connecté à Grid Manager à l'aide d'un navigateur pris en charge.
* Le nœud de stockage a été restauré et la restauration des données est terminée.


.Étapes
. Sélectionnez *support* > *Outils* > *topologie de grille*.
. Vérifiez les valeurs de *nœud de stockage récupéré* *LDR* *Storage* *Storage State -- désiré* et *Storage State -- courant*.
+
La valeur des deux attributs doit être en ligne.

. Si l'état de stockage -- souhaité est défini sur lecture seule, procédez comme suit :
+
.. Cliquez sur l'onglet *Configuration*.
.. Dans la liste déroulante *État de stockage -- désiré*, sélectionnez *en ligne*.
.. Cliquez sur *appliquer les modifications*.
.. Cliquez sur l'onglet *Présentation* et confirmez que les valeurs de *État de stockage -- désiré* et *État de stockage -- actuel* sont mises à jour en ligne.



