---
permalink: maintain/configuring-ip-addresses.html 
sidebar: sidebar 
keywords: storagegrid, ip address, configure ip address, configuring ip address, network configuration, network configure, network configuring 
summary: 'Vous pouvez configurer le réseau en configurant des adresses IP pour les noeuds de la grille à l"aide de l"outil Modifier les adresses IP.' 
---
= Configuration des adresses IP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer le réseau en configurant des adresses IP pour les noeuds de la grille à l'aide de l'outil Modifier les adresses IP.

Vous devez utiliser l'outil Modifier l'IP pour apporter la plupart des modifications à la configuration réseau qui ont été initialement définies lors du déploiement de la grille. Les modifications manuelles effectuées à l'aide de commandes et de fichiers de mise en réseau Linux standard peuvent ne pas se propager à tous les services StorageGRID et ne pas persister entre les mises à niveau, redémarrages ou les procédures de restauration des nœuds.


NOTE: Si vous souhaitez modifier l'adresse IP du réseau Grid pour tous les nœuds de la grille, utilisez la procédure spéciale pour les modifications au niveau de la grille.

link:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.html["Modification des adresses IP de tous les nœuds de la grille"]


NOTE: Si vous apportez uniquement des modifications à la liste de sous-réseaux du réseau Grid, utilisez le gestionnaire de grille pour ajouter ou modifier la configuration du réseau. Dans le cas contraire, utilisez l'outil Modifier IP si le gestionnaire de grille est inaccessible en raison d'un problème de configuration du réseau ou si vous effectuez une modification du routage du réseau Grid et d'autres modifications du réseau simultanément.


IMPORTANT: La procédure de modification IP peut être une procédure perturbateur. Des parties de la grille peuvent être indisponibles jusqu'à l'application de la nouvelle configuration.

*Interfaces Ethernet*

L'adresse IP attribuée à eth0 est toujours l'adresse IP réseau du nœud de la grille. L'adresse IP attribuée à eth1 est toujours l'adresse IP du réseau Admin du nœud de la grille. L'adresse IP attribuée à eth2 est toujours l'adresse IP du réseau client du nœud de la grille.

Notez que, sur certaines plateformes, comme les appliances StorageGRID, eth0, eth1 et eth2 peuvent être des interfaces agrégées composées de ponts subordonnés ou de liaisons d'interfaces physiques ou VLAN. Sur ces plates-formes, l'onglet *SSM* *Resources* peut afficher l'adresse IP de réseau Grid, Admin et client attribuée à d'autres interfaces en plus d'eth0, eth1 ou eth2.

*DHCP*

Vous ne pouvez configurer DHCP que pendant la phase de déploiement. Vous ne pouvez pas configurer DHCP pendant la configuration. Vous devez utiliser les procédures de modification d'adresse IP pour modifier les adresses IP, les masques de sous-réseau et les passerelles par défaut pour un nœud de grille. L'utilisation de l'outil Modifier les adresses IP va rendre les adresses DHCP statiques.

*Groupes haute disponibilité (HA)*

* Vous ne pouvez pas modifier l'adresse IP du réseau client en dehors du sous-réseau d'un groupe HA configuré sur l'interface réseau client.
* Vous ne pouvez pas remplacer l'adresse IP du réseau client par la valeur d'une adresse IP virtuelle existante attribuée par un groupe HA configuré sur l'interface réseau client.
* Vous ne pouvez pas modifier l'adresse IP du réseau Grid en dehors du sous-réseau d'un groupe HA configuré sur l'interface réseau Grid.
* Vous ne pouvez pas remplacer l'adresse IP du réseau Grid par la valeur d'une adresse IP virtuelle existante attribuée par un groupe HA configuré sur l'interface réseau Grid.


.Choix
* link:changing-nodes-network-configuration.html["Modification de la configuration réseau d'un nœud"]
* link:adding-to-or-changing-subnet-lists-on-admin-network.html["Ajout ou modification de listes de sous-réseaux sur le réseau d'administration"]
* link:adding-to-or-changing-subnet-lists-on-grid-network.html["Ajout ou modification de listes de sous-réseaux sur le réseau Grid"]
* link:linux-adding-interfaces-to-existing-node.html["Linux : ajout d'interfaces à un nœud existant"]
* link:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.html["Modification des adresses IP de tous les nœuds de la grille"]

