---
permalink: maintain/gathering-required-materials-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recovery, grid node recovery, node recovery 
summary: 'Avant d"effectuer des procédures de maintenance, vous devez vous assurer que vous disposez des matériaux nécessaires pour récupérer un nœud de grille défaillant.' 
---
= Collecte des matériaux nécessaires pour la restauration des nœuds du grid
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'effectuer des procédures de maintenance, vous devez vous assurer que vous disposez des matériaux nécessaires pour récupérer un nœud de grille défaillant.

[cols="1a,2a"]
|===
| Élément | Remarques 


 a| 
Archive de l'installation de StorageGRID
 a| 
Si vous devez restaurer un nœud de grid, vous avez besoin de l'archive d'installation de StorageGRID pour votre plateforme.

*Remarque :* vous n'avez pas besoin de télécharger de fichiers si vous récupérez des volumes de stockage défectueux sur un noeud de stockage.



 a| 
Package de restauration `.zip` fichier
 a| 
Obtenir une copie du dernier progiciel de récupération `.zip` fichier :
`sgws-recovery-package-_id-revision_.zip`

Le contenu du `.zip` le fichier est mis à jour chaque fois que le système est modifié. Vous êtes invité à stocker la version la plus récente du progiciel de restauration dans un emplacement sécurisé après avoir effectué de telles modifications. Utilisez la copie la plus récente pour récupérer des données suite à des défaillances du grid.

Si le nœud d'administration principal fonctionne normalement, vous pouvez télécharger le progiciel de restauration à partir de Grid Manager. Sélectionnez *Maintenance* *système* *progiciel de récupération*.

Si vous ne pouvez pas accéder à Grid Manager, vous pouvez trouver des copies chiffrées du progiciel de récupération sur certains nœuds de stockage qui contiennent le service ADC. Sur chaque nœud de stockage, examinez cet emplacement pour le progiciel de restauration : `/var/local/install/sgws-recovery-package-_grid-id_-_revision_.zip.gpg` Utilisez le progiciel de restauration avec le numéro de révision le plus élevé.



 a| 
`Passwords.txt` fichier
 a| 
Contient les mots de passe requis pour accéder aux nœuds de la grille sur la ligne de commande. Inclus dans le package de restauration.



 a| 
Phrase secrète pour le provisionnement
 a| 
La phrase de passe est créée et documentée lors de l'installation initiale du système StorageGRID. La phrase de passe de provisionnement n'est pas dans le `Passwords.txt` fichier.



 a| 
Documentation actuelle pour votre plate-forme
 a| 
Pour connaître les versions les plus récentes prises en charge de votre plateforme, consultez la matrice d'interopérabilité.

https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"]

Rendez-vous sur le site Web du fournisseur de la plate-forme pour obtenir de la documentation.

|===
.Informations associées
link:downloading-and-extracting-storagegrid-installation-files.html["Téléchargement et extraction des fichiers d'installation de StorageGRID"]

link:web-browser-requirements.html["Navigateurs Web pris en charge"]
