---
permalink: maintain/obtaining-required-materials-for-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: 'Avant d"appliquer un correctif, vous devez obtenir tous les matériaux requis.' 
---
= Obtenir les documents requis pour un correctif
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'appliquer un correctif, vous devez obtenir tous les matériaux requis.

[cols="1a,2a"]
|===
| Élément | Remarques 


 a| 
Fichier de correctif StorageGRID
 a| 
Vous devez télécharger le fichier de correctif StorageGRID.



 a| 
* Port réseau
* Navigateur Web pris en charge
* Client SSH (par exemple, PuTTY)

 a| 
Voir « exigences du navigateur Web ».



 a| 
Package de restauration (`.zip`) fichier
 a| 
Avant d'appliquer un correctif, téléchargez le fichier le plus récent du progiciel de récupération en cas de problème survenant pendant le correctif.ensuite, après l'application du correctif, téléchargez une nouvelle copie du fichier du progiciel de récupération et enregistrez-le dans un emplacement sûr. Le fichier du progiciel de récupération mis à jour vous permet de restaurer le système en cas de défaillance.



| Fichier Passwords.txt  a| 
Facultatif et utilisé uniquement si vous appliquez un correctif manuellement à l'aide du client SSH. Le `Passwords.txt` Le fichier est inclus dans LEDIT package, qui fait partie du progiciel de restauration `.zip` fichier.



 a| 
Phrase secrète pour le provisionnement
 a| 
La phrase de passe est créée et documentée lors de l'installation initiale du système StorageGRID. La phrase de passe de provisionnement n'est pas répertoriée dans le `Passwords.txt` fichier.



 a| 
Documentation associée
 a| 
`readme.txt` fichier du correctif. Ce fichier est inclus sur la page de téléchargement du correctif. N'oubliez pas de passer en revue le `readme` lifile soigneusement avant d'appliquer le correctif.

|===
.Informations associées
link:downloading-hotfix-file.html["Téléchargement du fichier de correctif"]

link:downloading-recovery-package.html["Téléchargement du progiciel de restauration"]
