---
permalink: maintain/removing-port-remaps.html 
sidebar: sidebar 
keywords: storagegrid, recover, remove port remap, removing port remap, port remap 
summary: 'Si vous souhaitez configurer un noeud final pour le service Load Balancer et que vous souhaitez utiliser un port qui a déjà été configuré en tant que port mappé sur d"un remappage de port, vous devez d"abord supprimer le plan de plan de port existant, sinon le noeud final ne sera pas effectif. Vous devez exécuter un script sur chaque nœud d"administration et nœud de passerelle qui comporte des ports en conflit et remappés pour supprimer toutes les mappes de ports du nœud.' 
---
= Suppression des mappages de port
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez configurer un noeud final pour le service Load Balancer et que vous souhaitez utiliser un port qui a déjà été configuré en tant que port mappé sur d'un remappage de port, vous devez d'abord supprimer le plan de plan de port existant, sinon le noeud final ne sera pas effectif. Vous devez exécuter un script sur chaque nœud d'administration et nœud de passerelle qui comporte des ports en conflit avec des mappages afin de supprimer tous les mappages de ports du nœud.


CAUTION: Cette procédure supprime tous les mappages de ports. Si vous devez conserver certains des plans, contactez le support technique.

Pour plus d'informations sur la configuration des terminaux de l'équilibreur de charge, reportez-vous aux instructions d'administration de StorageGRID.


IMPORTANT: Si le schéma de câblage du port fournit l'accès client, le client doit être reconfiguré de façon à utiliser un port différent configuré en tant que point de terminaison d'équilibreur de charge si possible, afin d'éviter une perte de service. Dans le cas contraire, la suppression du mappage des ports entraînera une perte d'accès client et devrait être planifiée de manière appropriée.


IMPORTANT: Cette procédure ne fonctionne pas pour un système StorageGRID déployé en tant que conteneur sur les hôtes bare Metal. Reportez-vous aux instructions de suppression des mappages de ports sur les hôtes bare Metal.

.Étapes
. Connectez-vous au nœud.
+
.. Saisissez la commande suivante : `ssh -p 8022 admin@node_IP`
+
Le port 8022 est le port SSH du système d'exploitation de base, tandis que le port 22 est le port SSH du conteneur Docker exécutant StorageGRID.

.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour passer à la racine : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



. Exécutez le script suivant : `remove-port-remap.sh`
. Redémarrez le nœud.
+
Suivez les instructions pour redémarrer un nœud de la grille.

. Répétez ces étapes sur chaque nœud d'administration et nœud de passerelle disposant de ports en conflit avec des ports remappés.


.Informations associées
link:../admin/index.html["Administrer StorageGRID"]

link:rebooting-grid-node.html["Redémarrage d'un nœud de grille"]

link:removing-port-remaps-on-bare-metal-hosts.html["Suppression de mappages de port sur les hôtes bare Metal"]
