---
permalink: maintain/replacing-storage-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, replace storage node, replacing storage node 
summary: 'Si le lecteur du système est défectueux, vous devez d"abord remplacer le nœud de stockage.' 
---
= Remplacement du nœud de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si le lecteur du système est défectueux, vous devez d'abord remplacer le nœud de stockage.

Vous devez sélectionner la procédure de remplacement de nœuds pour votre plate-forme. Les étapes à suivre pour remplacer un nœud sont les mêmes pour tous les types de nœuds de la grille.


NOTE: Cette procédure s'applique uniquement aux nœuds de stockage basés sur logiciel. Vous devez suivre une procédure différente pour restaurer un nœud de stockage d'appliance.

link:recovering-storagegrid-appliance-storage-node.html["Récupération d'un nœud de stockage d'appliance StorageGRID"]

*Linux:* si vous n'êtes pas sûr que votre lecteur système a échoué, suivez les instructions pour remplacer le nœud afin de déterminer quelles étapes de restauration sont nécessaires.

[cols="1a,2a"]
|===
| Plateforme | Procédure 


 a| 
VMware
 a| 
link:all-node-types-replacing-vmware-node.html["Remplacement d'un nœud VMware"]



 a| 
Linux
 a| 
link:all-node-types-replacing-linux-node.html["Remplacement d'un noeud Linux"]



 a| 
OpenStack
 a| 
Les fichiers et scripts de disques de machine virtuelle fournis par NetApp pour OpenStack ne sont plus pris en charge pour les opérations de restauration. Si vous devez restaurer un nœud exécuté dans un déploiement OpenStack, téléchargez les fichiers du système d'exploitation Linux. Suivez ensuite la procédure de remplacement d'un noeud Linux.

|===