---
permalink: maintain/stopping-server-manager-and-all-services.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop server manager, stop all services, stop services 
summary: 'Server Manager est conçu pour fonctionner en permanence, mais il peut être nécessaire d"arrêter Server Manager et tous les services exécutés sur un nœud de grille.' 
---
= Arrêt de Server Manager et de tous les services
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Server Manager est conçu pour fonctionner en permanence, mais il peut être nécessaire d'arrêter Server Manager et tous les services exécutés sur un nœud de grille.

.Ce dont vous avez besoin
Vous devez avoir le `Passwords.txt` fichier.

.Description de la tâche
Le seul scénario qui nécessite l'arrêt de Server Manager tout en maintenant le système d'exploitation en cours d'exécution est lorsque vous devez intégrer Server Manager à d'autres services. Si vous devez arrêter Server Manager pour la maintenance du matériel ou la reconfiguration du serveur, l'ensemble du serveur doit être arrêté.

.Étapes
. Connectez-vous au nœud grid :
+
.. Saisissez la commande suivante : `ssh admin@_grid_node_IP_`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour passer à la racine : `su -`
.. Entrez le mot de passe indiqué dans le `Passwords.txt` fichier.


+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.

. Arrêter Server Manager et tous les services exécutés sur le noeud grid : `service servermanager stop`
+
Server Manager et tous les services exécutés sur le nœud de la grille sont normalement terminés. L'arrêt des services peut prendre jusqu'à 15 minutes.

. Déconnectez-vous du shell de commande : `exit`

