---
permalink: maintain/storagegrid-hotfix-procedure.html 
sidebar: sidebar 
keywords:  
summary: Vous devrez peut-être appliquer un correctif à votre système StorageGRID si des problèmes liés au logiciel sont détectés et résolus entre les versions de fonctionnalités. 
---
= Procédure de correctif StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devrez peut-être appliquer un correctif à votre système StorageGRID si des problèmes liés au logiciel sont détectés et résolus entre les versions de fonctionnalités.

Les correctifs StorageGRID contiennent des modifications logicielles qui sont disponibles en dehors d'une version de fonctionnalité ou de correctif. Les mêmes modifications seront incluses dans une prochaine version. En outre, chaque version de correctif contient une synthèse de tous les correctifs précédents au sein de la fonction ou de la version de correctif.

* link:considerations-for-applying-hotfix.html["Considérations relatives à l'application d'un correctif"]
* link:how-your-system-is-affected-when-you-apply-hotfix.html["Quel est l'impact de votre système lorsque vous appliquez un correctif"]
* link:obtaining-required-materials-for-hotfix.html["Obtenir les documents requis pour un correctif"]
* link:downloading-hotfix-file.html["Téléchargement du fichier de correctif"]
* link:checking-systems-condition-before-applying-hotfix.html["Vérification de l'état du système avant d'appliquer un correctif"]
* link:applying-hotfix.html["Application du correctif"]

