---
permalink: maintain/troubleshooting-node-decommissioning.html 
sidebar: sidebar 
keywords: storagegrid, recover, decommission, troubleshoot 
summary: 'Si la procédure de mise hors service du nœud s"arrête à cause d"une erreur, vous pouvez prendre des étapes spécifiques pour résoudre le problème.' 
---
= Dépannage du déclassement du nœud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la procédure de mise hors service du nœud s'arrête à cause d'une erreur, vous pouvez prendre des étapes spécifiques pour résoudre le problème.

.Ce dont vous avez besoin
Vous devez être connecté à Grid Manager à l'aide d'un navigateur pris en charge.

.Description de la tâche
Si vous arrêtez le nœud de la grille en cours de mise hors service, la tâche s'arrête jusqu'au redémarrage du nœud de la grille. Le nœud grid doit être en ligne.

.Étapes
. Sélectionnez *support* > *Outils* > *topologie de grille*.
. Dans l'arborescence de la topologie grille, développez chaque entrée de noeud de stockage et vérifiez que les services DDS et LDR sont tous deux en ligne.
+
Pour mettre hors service un nœud de stockage, les services DDS du système StorageGRID (hébergés par des nœuds de stockage) doivent être en ligne. Cette étape est obligatoire pour la réévaluation du ILM.

. Pour afficher les tâches de la grille active, sélectionnez *nœud d'administration principal* *CMN* *tâches de la grille* *Présentation*.
. Vérifiez l'état de la tâche de grille de mise hors service.
+
.. Si l'état de la tâche de grille de mise hors service indique un problème avec l'enregistrement des ensembles de tâches de grille, sélectionnez *nœud d'administration principal* *CMN* *événements* *Présentation*
.. Vérifier le nombre de relais d'audit disponibles.
+
Si l'attribut Relais d'audit disponible est un ou plusieurs, le service CMN est connecté à au moins un service ADC. Les services ADC font office de relais d'audit.

+
Le service CMN doit être connecté à au moins un service ADC et une majorité (50 % plus un) des services ADC du système StorageGRID doit être disponible pour qu'une tâche de grille passe d'une étape de déclassement à une autre et se termine.

.. Si le service CMN n'est pas connecté à suffisamment de services ADC, assurez-vous que les nœuds de stockage sont en ligne et vérifiez la connectivité réseau entre le nœud d'administration principal et les nœuds de stockage.



