---
permalink: sg5700/configuring-hardware-sg5712-60.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking 
summary: 'Après avoir mis l"appliance sous tension, vous devez configurer SANtricity System Manager, qui est le logiciel que vous utiliserez pour surveiller le matériel. Vous devez également configurer les connexions réseau qui seront utilisées par StorageGRID.' 
---
= Configuration matérielle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir mis l'appliance sous tension, vous devez configurer SANtricity System Manager, qui est le logiciel que vous utiliserez pour surveiller le matériel. Vous devez également configurer les connexions réseau qui seront utilisées par StorageGRID.

.Étapes
* link:configuring-storagegrid-connections.html["Configuration des connexions StorageGRID"]
* link:accessing-and-configuring-santricity-system-manager.html["Accès et configuration de SANtricity System Manager"]
* link:optional-enabling-node-encryption.html["Facultatif : activation du chiffrement de nœud"]
* link:optional-changing-raid-mode-sg5760-only.html["Facultatif : modification du mode RAID (SG5760 uniquement)"]
* link:optional-remapping-network-ports-for-appliance-sg5600-and-sg5700.html["Facultatif : remappage des ports réseau de l'appliance"]

