---
permalink: expand/configuring-expanded-storagegrid-system.html 
sidebar: sidebar 
keywords: expansion, configuration 
summary: 'Une fois l"extension terminée, vous devez effectuer d"autres étapes d"intégration et de configuration.' 
---
= Configuration de votre système StorageGRID étendu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois l'extension terminée, vous devez effectuer d'autres étapes d'intégration et de configuration.

.Description de la tâche
Vous devez effectuer les tâches de configuration répertoriées ci-dessous pour les nœuds de la grille que vous ajoutez dans votre extension. Certaines tâches peuvent être facultatives, en fonction des options sélectionnées lors de l'installation et de l'administration de votre système et de la façon dont vous souhaitez configurer les nœuds de grille ajoutés lors de l'extension.

.Étapes
. Si vous avez ajouté un nœud de stockage, effectuez les tâches de configuration suivantes.
+
[cols="2a,1a"]
|===
| Tâches de configuration des nœuds de stockage | Pour plus d'informations 


 a| 
Vérifiez les pools de stockage utilisés dans vos règles ILM pour vous assurer que le nouveau stockage sera utilisé.

** Si vous avez ajouté un site, créez un pool de stockage pour le site et mettez à jour les règles ILM pour utiliser le nouveau pool de stockage.
** Si vous avez ajouté un nœud de stockage à un site existant, vérifiez que le nouveau nœud utilise la classe de stockage appropriée.
+
*Remarque :* par défaut, un nouveau nœud de stockage est affecté à la classe de stockage tous les nœuds de stockage et ajouté aux pools de stockage qui utilisent cette classe pour le site. Si vous souhaitez qu'un nouveau nœud utilise une note de stockage personnalisée, vous devez l'affecter manuellement à la note personnalisée (*ILM* > *notes de stockage*).


 a| 
link:../ilm/index.html["Gestion des objets avec ILM"]



 a| 
Vérifiez que le nœud de stockage capture des objets.
 a| 
link:verifying-storage-node-is-active.html["Vérification de l'état actif du nœud de stockage"]



 a| 
Rééquilibrez les données codées d'effacement (uniquement si vous n'avez pas pu ajouter le nombre recommandé de nœuds de stockage).
 a| 
link:rebalancing-erasure-coded-data-after-adding-storage-nodes.html["Rééquilibrage des données avec code d'effacement après l'ajout de nœuds de stockage"]

|===
. Si vous avez ajouté un nœud de passerelle, effectuez les tâches de configuration suivantes.
+
[cols="2a,1a"]
|===
| Tâches de configuration du nœud de passerelle | Pour plus d'informations 


 a| 
Si des groupes haute disponibilité sont utilisés pour les connexions client, ajoutez les nœuds de passerelle à un groupe haute disponibilité. Sélectionnez *Configuration* > *Paramètres réseau* > *groupes haute disponibilité* pour consulter la liste des groupes haute disponibilité existants et ajouter les nouveaux nœuds.
 a| 
link:../admin/index.html["Administrer StorageGRID"]

|===
. Si vous avez ajouté un nœud d'administration, effectuez les tâches de configuration suivantes.
+
[cols="2a,1a"]
|===
| Tâches de configuration du nœud d'administration | Pour plus d'informations 


 a| 
Si l'authentification unique est activée pour votre système StorageGRID, vous devez créer une confiance de partie de confiance dans Active Directory Federation Services (AD FS) pour le nouveau nœud d'administration. Vous ne pouvez pas vous connecter au nœud tant que vous n'avez pas créé cette confiance de partie de confiance.
 a| 
link:../admin/configuring-sso.html["Configuration de l'authentification unique"]



 a| 
Si vous prévoyez d'utiliser le service Load Balancer sur les nœuds d'administration, vous devrez peut-être ajouter des nœuds d'administration aux groupes haute disponibilité. Sélectionnez *Configuration* > *Paramètres réseau* > *groupes haute disponibilité* pour consulter la liste des groupes haute disponibilité existants et ajouter les nouveaux nœuds.
 a| 
link:../admin/index.html["Administrer StorageGRID"]



 a| 
Vous pouvez également copier la base de données du nœud d'administration principal vers le nœud d'administration d'extension si vous souhaitez préserver la cohérence des informations d'audit et d'attribut sur chaque nœud d'administration.
 a| 
link:copying-admin-node-database.html["Copie de la base de données du noeud d'administration"]



 a| 
Si vous souhaitez conserver la cohérence des metrics historiques sur chaque nœud d'administration, vous pouvez également copier la base de données Prometheus du nœud d'administration principal vers le nœud d'administration d'extension.
 a| 
link:copying-prometheus-metrics.html["Copie des metrics Prometheus"]



 a| 
Si vous souhaitez conserver la cohérence des informations du journal historique sur chaque nœud d'administration, copiez les journaux d'audit existants du nœud d'administration principal vers le nœud d'administration d'extension.
 a| 
link:copying-audit-logs.html["Copie des journaux d'audit"]



 a| 
Vous pouvez également configurer l'accès au système à des fins d'audit via un partage de fichiers NFS ou CIFS.

*Note:* l'exportation d'audit via CIFS/Samba a été obsolète et sera supprimée dans une future version de StorageGRID.
 a| 
link:../admin/index.html["Administrer StorageGRID"]



 a| 
Vous pouvez également modifier l'expéditeur préféré pour les notifications. Vous pouvez faire du nœud d'administration d'extension l'expéditeur préféré. Sinon, un nœud d'administration existant configuré comme expéditeur préféré continue à envoyer des notifications, notamment des messages AutoSupport, des notifications SNMP, des e-mails d'alerte et des e-mails d'alarme (système existant).
 a| 
link:../admin/index.html["Administrer StorageGRID"]

|===
. Si vous avez ajouté un noeud d'archivage, effectuez les tâches de configuration suivantes.
+
[cols="2a,1a"]
|===
| Tâches de configuration du nœud d'archivage | Pour plus d'informations 


 a| 
Configurez la connexion du nœud d'archivage au système de stockage d'archivage externe cible. Lorsque vous terminez l'extension, les nœuds d'archivage sont en état d'alarme jusqu'à ce que vous configuriez les informations de connexion via le composant *ARC* > *cible*.
 a| 
link:../admin/index.html["Administrer StorageGRID"]



 a| 
Mettre à jour la politique ILM pour archiver les données d'objet via le nouveau nœud d'archivage.
 a| 
link:../ilm/index.html["Gestion des objets avec ILM"]



 a| 
Configurez des alarmes personnalisées pour les attributs utilisés pour surveiller la vitesse et l'efficacité de la récupération des données d'objet à partir des nœuds d'archivage.
 a| 
link:../admin/index.html["Administrer StorageGRID"]

|===
. Pour vérifier si des nœuds d'extension ont été ajoutés avec un réseau client non fiable ou pour modifier si le réseau client d'un nœud n'est pas fiable ou approuvé, accédez à *Configuration* > *Paramètres réseau* > *réseau client non fiable*.
+
Si le réseau client sur le nœud d'extension n'est pas fiable, les connexions au nœud sur le réseau client doivent être effectuées à l'aide d'un noeud final d'équilibreur de charge. Pour plus d'informations, reportez-vous aux instructions d'administration de StorageGRID.

. Configuration du DNS (Domain Name System).
+
Si vous avez spécifié des paramètres DNS séparément pour chaque nœud de grid, vous devez ajouter des paramètres DNS personnalisés par nœud pour les nouveaux nœuds. Reportez-vous à la section informations sur la modification de la configuration DNS pour un nœud grille unique dans les instructions de restauration et de maintenance.

+
La meilleure pratique consiste à ce que la liste des serveurs DNS dans le grid contienne certains serveurs DNS accessibles localement à partir de chaque site. Si vous venez d'ajouter un nouveau site, ajoutez de nouveaux serveurs DNS pour le site à la configuration DNS à l'échelle de la grille.

+

IMPORTANT: Fournir deux à six adresses IPv4 pour les serveurs DNS. Vous devez sélectionner des serveurs DNS auxquels chaque site peut accéder localement en cas d'isatterissage du réseau. Cela permet de s'assurer qu'un site isatterri continue d'avoir accès au service DNS. Après avoir configuré la liste des serveurs DNS au niveau de la grille, vous pouvez personnaliser davantage la liste des serveurs DNS pour chaque nœud. Pour plus de détails, reportez-vous aux informations sur la modification de la configuration DNS dans les instructions de récupération et de maintenance.

. Si vous avez ajouté un nouveau site, confirmez que les serveurs NTP (Network Time Protocol) sont accessibles à partir de ce site.
+

IMPORTANT: Assurez-vous qu'au moins deux nœuds de chaque site peuvent accéder à au moins quatre sources NTP externes. Si un seul nœud d'un site peut atteindre les sources NTP, des problèmes de synchronisation surviennent en cas de panne de ce nœud. En outre, la désignation de deux nœuds par site en tant que sources NTP principales assure une synchronisation précise si un site est isolé du reste de la grille.

+
Pour plus d'informations, reportez-vous aux instructions de récupération et d'entretien.



.Informations associées
link:../ilm/index.html["Gestion des objets avec ILM"]

link:verifying-storage-node-is-active.html["Vérification de l'état actif du nœud de stockage"]

link:copying-admin-node-database.html["Copie de la base de données du noeud d'administration"]

link:copying-prometheus-metrics.html["Copie des metrics Prometheus"]

link:copying-audit-logs.html["Copie des journaux d'audit"]

link:../upgrade/index.html["Mise à niveau du logiciel"]

link:../maintain/index.html["Maintenance et récupération"]
