---
permalink: expand/preparing-for-expansion.html 
sidebar: sidebar 
keywords: expand, expansion, planning 
summary: 'Vous devez préparer l"extension StorageGRID en obtenant les ressources requises et en installant et configurant de nouveaux matériels et réseaux.' 
---
= Préparation d'une expansion
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez préparer l'extension StorageGRID en obtenant les ressources requises et en installant et configurant de nouveaux matériels et réseaux.



== Collecte des matériaux nécessaires

Avant d'effectuer une opération d'expansion, vous devez rassembler les matériaux répertoriés dans le tableau suivant.

[cols="1a,2a"]
|===
| Élément | Remarques 


 a| 
Archive de l'installation de StorageGRID
 a| 
Si vous ajoutez de nouveaux nœuds de grille ou un nouveau site, vous devez télécharger et extraire l'archive d'installation de StorageGRID. Vous devez utiliser la même version que celle actuellement en cours d'exécution sur la grille.

Pour plus de détails, reportez-vous aux instructions de téléchargement et d'extraction des fichiers d'installation de StorageGRID.

*Remarque :* vous n'avez pas besoin de télécharger de fichiers si vous ajoutez de nouveaux volumes de stockage à des nœuds de stockage existants ou si vous installez une nouvelle appliance StorageGRID.



 a| 
L'ordinateur portable de service
 a| 
L'ordinateur portable de service doit répondre aux exigences suivantes :

* Port réseau
* Client SSH (par exemple, PuTTY)
* Navigateur pris en charge




 a| 
Phrase secrète pour le provisionnement
 a| 
La phrase de passe est créée et documentée lors de l'installation initiale du système StorageGRID. La phrase de passe de provisionnement n'est pas dans le `Passwords.txt` fichier.



 a| 
Documentation StorageGRID
 a| 
* _Administration de StorageGRID_
* _StorageGRID Notes de mise à jour_
* Instructions d'installation pour votre plate-forme




 a| 
Documentation actuelle pour votre plate-forme
 a| 
Pour connaître les versions prises en charge, consultez la matrice d'interopérabilité.

|===
.Informations associées
link:../admin/index.html["Administrer StorageGRID"]

link:../release-notes/index.html["Notes de mise à jour"]

link:../vmware/index.html["Installez VMware"]

link:../rhel/index.html["Installez Red Hat Enterprise Linux ou CentOS"]

link:../ubuntu/index.html["Installez Ubuntu ou Debian"]

https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^]



=== Navigateurs Web pris en charge

Vous devez utiliser un navigateur Web pris en charge.

[cols="1a,1a"]
|===
| Navigateur Web | Version minimale prise en charge 


 a| 
Google Chrome
 a| 
87



 a| 
Microsoft Edge
 a| 
87



 a| 
Mozilla Firefox
 a| 
84

|===
Vous devez régler la fenêtre du navigateur sur une largeur recommandée.

[cols="1a,1a"]
|===
| Largeur du navigateur | Pixels 


 a| 
Minimum
 a| 
1024



 a| 
Optimale
 a| 
1280

|===


== Téléchargement et extraction des fichiers d'installation de StorageGRID

Avant de pouvoir ajouter de nouveaux nœuds de grille ou un nouveau site, vous devez télécharger l'archive d'installation StorageGRID appropriée et extraire les fichiers.

.Description de la tâche
Vous devez effectuer des opérations d'extension à l'aide de la version de StorageGRID actuellement exécutée sur la grille.

.Étapes
. Accédez à la page de téléchargements NetApp pour StorageGRID.
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Téléchargement NetApp : StorageGRID"^]

. Sélectionnez la version de StorageGRID en cours d'exécution sur la grille.
. Connectez-vous avec le nom d'utilisateur et le mot de passe de votre compte NetApp.
. Lisez le contrat de licence de l'utilisateur final, cochez la case, puis sélectionnez *accepter et continuer*.
. Dans la colonne *installer StorageGRID* de la page de téléchargement, sélectionnez `.tgz` ou `.zip` fichier pour votre plate-forme.
+
La version affichée dans le fichier d'archive d'installation doit correspondre à la version du logiciel actuellement installé.

+
Utilisez le `.zip` Fichier si vous exécutez Windows sur l'ordinateur portable de service.

+
[cols="1a,1a"]
|===
| Plateforme | Archive d'installation 


 a| 
VMware
| StorageGRID-Webscale-_version_-VMware-_uniqueID_.zip StorageGRID-Webscale-_version_-VMware-_uniqueID_.tgz 


 a| 
Red Hat Enterprise Linux ou CentOS
| StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz 


 a| 
Ubuntu ou Debian et Appliance
| StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz 


 a| 
OpenStack/autre hyperviseur
 a| 
Pour étendre un déploiement existant sur OpenStack, vous devez déployer une machine virtuelle exécutant l'une des distributions Linux prises en charge répertoriées ci-dessus et suivre les instructions appropriées pour Linux.

|===
. Téléchargez et extrayez le fichier d'archive.
. Suivez les étapes appropriées pour votre plate-forme afin de choisir les fichiers dont vous avez besoin, en fonction de votre plate-forme, de la topologie de grille planifiée et de la manière dont vous allez étendre votre système StorageGRID.
+
Les chemins répertoriés dans l'étape pour chaque plate-forme sont relatifs au répertoire de niveau supérieur installé par le fichier d'archive.

. Si vous étendez un système VMware, sélectionnez les fichiers appropriés.
+
[cols="1a,1a"]
|===
| Chemin d'accès et nom de fichier | Description 


| ./vsphere/README  a| 
Fichier texte qui décrit tous les fichiers contenus dans le fichier de téléchargement StorageGRID.



| ./vsphere/NLF000000.txt  a| 
Licence gratuite qui ne fournit aucun droit d'assistance pour le produit.



| ./vsphere/NetApp-SG-_version_-SHA.vmdk  a| 
Fichier de disque de machine virtuelle utilisé comme modèle pour créer des machines virtuelles de nœud de grille.



| ./vsphere/vsphere-primary-admin.ovf ./vsphere/vsphere-primary-admin.mf  a| 
Fichier modèle du format Open Virtualization (`.ovf`) et fichier manifeste (`.mf`) Pour le déploiement du nœud d'administration principal.



| ./vsphere/vsphere-non-primary-admin.ovf ./vsphere/vsphere-non-primary-admin.mf  a| 
Le fichier de modèle (`.ovf`) et fichier manifeste (`.mf`) Pour le déploiement de nœuds d'administration non primaires.



| ./vsphere/vsphere-archive.ovf ./vsphere/vsphere-archive.mf  a| 
Le fichier de modèle (`.ovf`) et fichier manifeste (`.mf`) Pour le déploiement des nœuds d'archivage.



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
Le fichier de modèle (`.ovf`) et fichier manifeste (`.mf`) Pour le déploiement des nœuds de passerelle.



| ./vsphere/vsphere-storage.ovf ./vsphere/vsphere-storage.mf  a| 
Le fichier de modèle (`.ovf`) et fichier manifeste (`.mf`) Pour le déploiement de nœuds de stockage basés sur des machines virtuelles.



| Outil de script de déploiement | Description 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
Script de shell de Bash utilisé pour automatiser le déploiement de nœuds de grille virtuels.



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
Exemple de fichier de configuration à utiliser avec le `deploy-vsphere-ovftool.sh` script.



| ./vsphere/configure-storagegrid.py  a| 
Script Python utilisé pour automatiser la configuration d'un système StorageGRID.



| ./vsphere/configure-sga.py  a| 
Script Python utilisé pour automatiser la configuration des appliances StorageGRID.



| ./vsphere/storagegrid-ssoauth.py  a| 
Exemple de script Python que vous pouvez utiliser pour vous connecter à l'API Grid Management lorsque l'authentification unique est activée.



| ./vsphere/configure-storagegrid.sample.json  a| 
Exemple de fichier de configuration à utiliser avec le `configure-storagegrid.py` script.



| ./vsphere/configure-storagegrid.blank.json  a| 
Un fichier de configuration vierge à utiliser avec le `configure-storagegrid.py` script.

|===
. Si vous étendez un système Red Hat Enterprise Linux ou CentOS, sélectionnez les fichiers appropriés.
+
[cols="1a,1a"]
|===
| Chemin d'accès et nom de fichier | Description 


| ./rpms/README  a| 
Fichier texte qui décrit tous les fichiers contenus dans le fichier de téléchargement StorageGRID.



| ./rpms/NLF000000.txt  a| 
Licence gratuite qui ne fournit aucun droit d'assistance pour le produit.



| ./rpms/StorageGRID-Webscale-Images-version-SHA.rpm  a| 
Package RPM pour l'installation des images des nœuds StorageGRID sur vos hôtes RHEL ou CentOS.



| ./rpms/StorageGRID-Webscale-Service-version-SHA.rpm  a| 
Package RPM pour l'installation du service hôte StorageGRID sur vos hôtes RHEL ou CentOS.



| Outil de script de déploiement | Description 


| ./rpms/configure-storagegrid.py  a| 
Script Python utilisé pour automatiser la configuration d'un système StorageGRID.



| ./rpms/configure-sga.py  a| 
Script Python utilisé pour automatiser la configuration des appliances StorageGRID.



| ./rpms/configure-storagegrid.sample.json  a| 
Exemple de fichier de configuration à utiliser avec le `configure-storagegrid.py` script.



| ./rpms/storagegrid-ssoauth.py  a| 
Exemple de script Python que vous pouvez utiliser pour vous connecter à l'API Grid Management lorsque l'authentification unique est activée.



| ./rpms/configure-storagegrid.blank.json  a| 
Un fichier de configuration vierge à utiliser avec le `configure-storagegrid.py` script.



| ./rpms/extras/ansible  a| 
Exemple de rôle et de manuel de vente Ansible pour la configuration des hôtes RHEL ou CentOS pour le déploiement de conteneurs StorageGRID. Vous pouvez personnaliser le rôle ou le PlayBook selon vos besoins.

|===
. Si vous étendez un système Ubuntu ou Debian, sélectionnez les fichiers appropriés.
+
[cols="1a,1a"]
|===
| Chemin d'accès et nom de fichier | Description 


| ./bps/README  a| 
Fichier texte qui décrit tous les fichiers contenus dans le fichier de téléchargement StorageGRID.



| ./Debian/NLF000000.txt  a| 
Un fichier de licence NetApp hors production que vous pouvez utiliser pour tester et réaliser des démonstrations de faisabilité.



| ./Debian/storagegrid-webscale-images-version-SHA.deb  a| 
DEB paquet pour installer les images de noeud StorageGRID sur des hôtes Ubuntu ou Debian.



| ./Debian/storagegrid-webscale-images-version-SHA.deb.md5  a| 
Somme de contrôle MD5 pour le fichier `/debs/storagegrid-webscale-images-version-SHA.deb`.



| ./Debian/storagegrid-webscale-service-version-SHA.deb  a| 
Paquet DEB pour l'installation du service hôte StorageGRID sur des hôtes Ubuntu ou Debian.



| Outil de script de déploiement | Description 


| ./debian/configure-storagegrid.py  a| 
Script Python utilisé pour automatiser la configuration d'un système StorageGRID.



| ./debian/configure-sga.py  a| 
Script Python utilisé pour automatiser la configuration des appliances StorageGRID.



| ./debian/storagegrid-ssoauth.py  a| 
Exemple de script Python que vous pouvez utiliser pour vous connecter à l'API Grid Management lorsque l'authentification unique est activée.



| ./deps/configure-storagegrid.sample.json  a| 
Exemple de fichier de configuration à utiliser avec le `configure-storagegrid.py` script.



| ./deps/configure-storagegrid.blank.json  a| 
Un fichier de configuration vierge à utiliser avec le `configure-storagegrid.py` script.



| ./deps/extras/ansible  a| 
Exemple de rôle et de manuel de vente Ansible pour la configuration des hôtes Ubuntu ou Debian pour le déploiement de conteneurs StorageGRID. Vous pouvez personnaliser le rôle ou le PlayBook selon vos besoins.

|===
. Si vous étendez un système basé sur l'appliance StorageGRID, sélectionnez les fichiers appropriés.
+
[cols="1a,1a"]
|===
| Chemin d'accès et nom de fichier | Description 


| ./Debian/storagegrid-webscale-images-version-SHA.deb  a| 
DEB package pour l'installation des images de noeud StorageGRID sur vos appareils.



| ./Debian/storagegrid-webscale-images-version-SHA.deb.md5  a| 
Somme de contrôle du package d'installation de DEO utilisé par le programme d'installation de l'appliance StorageGRID pour vérifier que le package est intact après le téléchargement.

|===
+

NOTE: Pour l'installation de l'appliance, ces fichiers ne sont nécessaires que si vous devez éviter le trafic réseau. L'appliance peut télécharger les fichiers requis à partir du nœud d'administration principal.





== Vérification du matériel et du réseau

Avant de commencer l'extension de votre système StorageGRID, vous devez vous assurer que vous avez installé et configuré le matériel nécessaire pour prendre en charge les nouveaux nœuds de grid ou le nouveau site.

Pour plus d'informations sur les versions prises en charge, voir la matrice d'interopérabilité.

Vous devez également vérifier la connectivité réseau entre les serveurs du site et confirmer que le nœud d'administration principal peut communiquer avec tous les serveurs d'extension destinés à héberger le système StorageGRID.

Si vous effectuez une activité d'extension incluant l'ajout d'un nouveau sous-réseau, vous devez ajouter le nouveau sous-réseau Grid avant de lancer la procédure d'extension.

N'utilisez pas la traduction d'adresse réseau (NAT) sur le réseau de grille entre les nœuds de la grille ou entre les sites StorageGRID. Lorsque vous utilisez des adresses IPv4 privées pour le réseau Grid, ces adresses doivent être directement routables à partir de chaque nœud de la grille sur chaque site. Toutefois, vous pouvez utiliser NAT entre des clients externes et des nœuds de grille, par exemple pour fournir une adresse IP publique pour un nœud de passerelle. L'utilisation de la fonction NAT pour relier un segment de réseau public n'est prise en charge que lorsque vous utilisez une application de tunneling transparente pour tous les nœuds de la grille, ce qui signifie que les nœuds de la grille ne nécessitent aucune connaissance des adresses IP publiques.

*Informations connexes*

https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^]

link:updating-subnets-for-grid-network.html["Mise à jour des sous-réseaux pour le réseau Grid"]
