---
permalink: expand/verifying-storage-node-is-active.html 
sidebar: sidebar 
keywords: expand, expansion, add storage nodes, verify node is active 
summary: 'Une fois une opération d"extension qui ajoute de nouveaux nœuds de stockage terminée, le système StorageGRID doit démarrer automatiquement à l"aide des nouveaux nœuds de stockage. Vous devez utiliser le système StorageGRID pour vérifier que le nouveau nœud de stockage est actif.' 
---
= Vérification de l'état actif du nœud de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois une opération d'extension qui ajoute de nouveaux nœuds de stockage terminée, le système StorageGRID doit démarrer automatiquement à l'aide des nouveaux nœuds de stockage. Vous devez utiliser le système StorageGRID pour vérifier que le nouveau nœud de stockage est actif.

.Étapes
. Connectez-vous au Grid Manager à l'aide d'un navigateur pris en charge.
. Sélectionnez *Nodes* > *_expansion Storage Node_* > *Storage*.
. Placez le curseur sur le graphique *stockage utilisé - données objet* pour afficher la valeur de *utilisé*, qui correspond à la quantité d'espace utilisable total utilisée pour les données d'objet.
. Vérifiez que la valeur de *utilisé* augmente au fur et à mesure que vous déplacez le curseur vers la droite du graphique.

