---
permalink: troubleshoot/troubleshooting-delivery-platform-services-messages.html 
sidebar: sidebar 
keywords:  
summary: 'L"alarme Total Events (SMTT) est déclenchée dans Grid Manager si un message de service de plate-forme est envoyé à une destination qui ne peut pas accepter les données.' 
---
= Résolution des problèmes de transmission des messages des services de plate-forme (alarme SMTT)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'alarme Total Events (SMTT) est déclenchée dans Grid Manager si un message de service de plate-forme est envoyé à une destination qui ne peut pas accepter les données.

.Description de la tâche
Par exemple, un téléchargement partitionné S3 peut réussir même si le message de réplication ou de notification associé ne peut pas être transmis au noeud final configuré. Ou bien, un message pour la réplication CloudMirror peut ne pas être livré si les métadonnées sont trop longues.

L'alarme SMTT contient un message du dernier événement qui indique : `Failed to publish notifications for _bucket-name object key_` pour le dernier objet dont la notification a échoué.

Pour plus d'informations sur le dépannage des services de plate-forme, reportez-vous aux instructions d'administration de StorageGRID. Vous devrez peut-être accéder au locataire à partir du gestionnaire des locataires pour déboguer une erreur du service de plateforme.

.Étapes
. Pour afficher l'alarme, sélectionnez *noeuds* *_site_* *_grid node_* *Events*.
. Afficher le dernier événement en haut du tableau.
+
Les messages d'événement sont également répertoriés dans le `/var/local/log/bycast-err.log`.

. Suivez les instructions fournies dans le contenu de l'alarme SMTT pour corriger le problème.
. Cliquez sur *Réinitialiser le nombre d'événements*.
. Notifier le locataire des objets dont les messages de services de plate-forme n'ont pas été livrés.
. Demandez au locataire de déclencher l'échec de la réplication ou de la notification en mettant à jour les métadonnées ou balises de l'objet.


.Informations associées
link:../admin/index.html["Administrer StorageGRID"]

link:../tenant/index.html["Utilisez un compte de locataire"]

link:../monitor/logs-files-reference.html["Référence des fichiers journaux"]

link:../monitor/resetting-event-counts.html["Réinitialisation du nombre d'événements"]
