---
permalink: ilm/how-objects-are-deleted.html 
sidebar: sidebar 
keywords:  
summary: 'StorageGRID peut supprimer des objets en réponse directe à une requête d"un client ou automatiquement à la suite de l"expiration du cycle de vie d"un compartiment S3 ou des exigences de la politique ILM. Pour gérer plus efficacement les objets, il est important de comprendre les différentes méthodes de suppression des objets et la façon dont StorageGRID les gère.' 
---
= Comment supprimer les objets
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID peut supprimer des objets en réponse directe à une requête d'un client ou automatiquement à la suite de l'expiration du cycle de vie d'un compartiment S3 ou des exigences de la politique ILM. Pour gérer plus efficacement les objets, il est important de comprendre les différentes méthodes de suppression des objets et la façon dont StorageGRID les gère.

StorageGRID peut utiliser l'une des deux méthodes suivantes pour supprimer les objets :

* Suppression synchrone : lorsque StorageGRID reçoit une demande de suppression de client, toutes les copies d'objet sont supprimées immédiatement. Le client est informé que la suppression a réussi une fois les copies supprimées.
* Les objets sont placés en file d'attente pour suppression : lorsque StorageGRID reçoit une requête de suppression, l'objet est mis en attente pour suppression et le client est immédiatement informé de l'réussie de cette suppression. Les copies d'objet sont supprimées ultérieurement par le traitement ILM en arrière-plan.


Lors de la suppression d'objets, StorageGRID utilise la méthode qui optimise les performances de suppression, réduit les retards de suppression et libère de l'espace le plus rapidement possible.

Le tableau résume le moment où StorageGRID utilise chaque méthode.

[cols="1a,2a"]
|===
| Méthode d'exécution de la suppression | Lorsqu'il est utilisé 


 a| 
Les objets sont placés en file d'attente pour suppression
 a| 
Lorsque *l'une* des conditions suivantes est vraie :

* La suppression automatique d'objet a été déclenchée par l'un des événements suivants :
+
** La date d'expiration ou le nombre de jours pendant la configuration du cycle de vie d'un compartiment S3 est atteint.
** La dernière période spécifiée dans une règle ILM s'écoule.


+
*Remarque :* les objets d'un compartiment dont le verrouillage d'objet S3 est activé ne peuvent pas être supprimés s'ils sont en attente légale ou si une date de conservation a été spécifiée mais pas encore remplie.

* Un client S3 ou Swift demande la suppression d'une ou plusieurs des conditions suivantes :
+
** Les copies ne peuvent pas être supprimées dans les 30 secondes, car un emplacement d'objet est temporairement indisponible, par exemple.
** Les files d'attente de suppression d'arrière-plan sont inactives.






 a| 
Suppression immédiate d'objets (suppression synchrone)
 a| 
Lorsqu'un client S3 ou Swift effectue une demande de suppression et *toutes* des conditions suivantes sont remplies :

* Toutes les copies peuvent être supprimées en 30 secondes.
* Les files d'attente de suppression d'arrière-plan contiennent des objets à traiter.


|===
Lorsque les clients S3 ou Swift font des demandes de suppression, StorageGRID commence par ajouter un certain nombre d'objets à la file d'attente de suppression. Il passe ensuite en mode suppression synchrone. S'assurer que la file d'attente de suppression en arrière-plan contient des objets à traiter, ce qui permet à StorageGRID de traiter les suppressions plus efficacement, en particulier pour les clients à faible simultanéité, tout en aidant à empêcher la suppression des arriérés du client.



== Présentation de l'impact de la suppression d'objets par StorageGRID

La façon dont StorageGRID supprime des objets peut avoir un impact sur le fonctionnement du système :

* Lorsque StorageGRID effectue une suppression synchrone, StorageGRID peut donner jusqu'à 30 secondes pour renvoyer un résultat au client. Cela signifie que la suppression peut se produire plus lentement, même si les copies sont réellement supprimées plus rapidement que lors de la mise en file d'attente d'objets StorageGRID pour suppression.
* Si vous surveillez de près les performances de suppression lors d'une suppression en bloc, vous remarquerez que ce taux de suppression semble ralentir après la suppression d'un certain nombre d'objets. Ce changement survient lorsque StorageGRID passe d'objets de mise en file d'attente pour suppression à des fins de suppression synchrone. La réduction apparente du taux de suppression ne signifie pas que les copies d'objet sont supprimées plus lentement. Au contraire, elle indique qu'en moyenne, l'espace est maintenant libéré plus rapidement.


Si vous supprimez un grand nombre d'objets et que vous souhaitez libérer rapidement de l'espace, pensez à utiliser une requête client pour supprimer des objets au lieu de les supprimer à l'aide d'ILM ou d'autres méthodes. En général, l'espace est libéré plus rapidement lors de la suppression d'espace par les clients, car StorageGRID peut utiliser la suppression synchrone.

Notez que le temps nécessaire pour libérer de l'espace après la suppression d'un objet dépend de plusieurs facteurs :

* Si les copies d'objet sont supprimées de manière synchrone ou mises en file d'attente pour être supprimées ultérieurement (pour les demandes de suppression de client).
* D'autres facteurs, tels que le nombre d'objets dans la grille ou la disponibilité des ressources de la grille lorsque les copies d'objet sont mises en file d'attente pour suppression (pour les suppressions de clients et d'autres méthodes).

