---
permalink: ilm/removing-storage-pool.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez supprimer un pool de stockage qui n"est pas utilisé.' 
---
= Suppression d'un pool de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez supprimer un pool de stockage qui n'est pas utilisé.

.Ce dont vous avez besoin
* Vous devez être connecté à Grid Manager à l'aide d'un navigateur pris en charge.
* Vous devez disposer d'autorisations d'accès spécifiques.


.Étapes
. Sélectionnez *ILM* > *pools de stockage*.
+
La page Storage pools s'affiche.

. Consultez la colonne utilisation ILM du tableau pour déterminer si vous pouvez supprimer le pool de stockage.
+
Vous ne pouvez pas supprimer un pool de stockage s'il est utilisé dans une règle ILM ou dans un profil de code d'effacement. Selon les besoins, sélectionnez *View Details* > *ILM usage* pour déterminer où un pool de stockage est utilisé.

. Si le pool de stockage que vous souhaitez supprimer n'est pas utilisé, sélectionnez la case d'option.
. Sélectionnez *Supprimer*.
. Sélectionnez *OK*.

