---
permalink: fabricpool/example-ilm-policy-for-fabricpool-data.html 
sidebar: sidebar 
keywords: fabricPool, ilm, information lifecycle management, ILM policy, example 
summary: Utilisez cet exemple simple de règle comme point de départ pour vos propres règles et règles ILM. 
---
= Exemple de règle ILM pour les données FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilisez cet exemple simple de règle comme point de départ pour vos propres règles et règles ILM.

Nous partons du principe que vous concevez les règles ILM et une règle ILM pour un système StorageGRID qui possède quatre nœuds de stockage dans un data Center unique à Denver, Colorado. Les données FabricPool dans cet exemple utilisent un compartiment nommé `fabricpool-bucket`.

[CAUTION]
====
Les règles et règles ILM suivantes ne sont que des exemples. Les règles ILM sont nombreuses. Avant d'activer une nouvelle stratégie, simulez la stratégie proposée pour confirmer qu'elle fonctionnera comme destinée à protéger le contenu contre la perte.

Pour en savoir plus : link:../ilm/index.html["Gestion des objets avec ILM"]

====
.Étapes
. Créez un pool de stockage nommé *DEN*. Sélectionnez le site Denver.
. Créez un profil de code d'effacement nommé *2 plus 1*. Sélectionnez le schéma de code d'effacement 2+1 et le pool de stockage *DEN*.
. Créez une règle ILM qui s'applique uniquement aux données dans `fabricpool-bucket`. Dans cet exemple de règle, des copies avec code d'effacement sont créées.
+
[cols="1a,1a"]
|===
| Définition de règle | Exemple de valeur 


 a| 
Nom de la règle
 a| 
2 et 1 code d'effacement pour données FabricPool



 a| 
Nom du compartiment
 a| 
`fabricpool-bucket`

Vous pouvez également filtrer le compte de tenant FabricPool.



 a| 
Filtrage avancé
 a| 
Taille de l'objet (Mo) supérieure à 0.2 Mo.

*Remarque :* FabricPool écrit uniquement des objets de 4 Mo, mais vous devez ajouter un filtre de taille d'objet car cette règle utilise le codage d'effacement.



 a| 
Heure de référence
 a| 
Temps d'ingestion



 a| 
Positionnement
 a| 
À partir du jour 0 magasin pour toujours



 a| 
Type
 a| 
Code d'effacement



 a| 
Emplacement
 a| 
DEN (2 plus 1)



 a| 
Comportement d'ingestion
 a| 
Équilibré

|===
. Créez une règle ILM pour créer deux copies répliquées de tout objet ne correspondant pas à la première règle. Ne sélectionnez pas de filtre de base (compte de locataire ou nom de compartiment) ni de filtres avancés.
+
[cols="1a,1a"]
|===
| Définition de règle | Exemple de valeur 


 a| 
Nom de la règle
 a| 
Deux copies répliquées



 a| 
Nom du compartiment
 a| 
_aucun_



 a| 
Filtrage avancé
 a| 
_aucun_



 a| 
Heure de référence
 a| 
Temps d'ingestion



 a| 
Positionnement
 a| 
À partir du jour 0 magasin pour toujours



 a| 
Type
 a| 
Copies Snapshot



 a| 
Emplacement
 a| 
DEN



 a| 
Copies
 a| 
2



 a| 
Comportement d'ingestion
 a| 
Équilibré

|===
. Création d'une règle ILM proposée et sélection des deux règles Comme la règle de réplication n'utilise aucun filtre, elle peut être la règle par défaut (dernière) de la règle.
. Ingestion des objets de test dans la grille.
. Simuler la règle avec les objets de test pour vérifier le comportement.
. Activer la règle.


Lorsque cette règle est activée, StorageGRID place les données d'objet comme suit :

* Les données sont hiérarchisées à partir du système FabricPool In `fabricpool-bucket` le code d'effacement sera appliqué à l'aide du schéma de code d'effacement 2+1. Deux fragments de données et un fragment de parité seront placés sur trois nœuds de stockage différents.
* Tous les objets dans tous les autres compartiments sont répliqués. Deux copies sont créées et placées sur deux nœuds de stockage différents.
* Les copies répliquées et avec code d'effacement sont conservées dans StorageGRID jusqu'à leur suppression par le client S3. StorageGRID ILM ne supprimera jamais ces éléments.

