---
permalink: fabricpool/using-storagegrid-ilm-with-fabricpool-data.html 
sidebar: sidebar 
keywords: FabricPool, requirements, ILM, information lifecycle management, ILM rule, ILM rules, ILM policy, erasure-coding, replication, cloud storage pool, glacier 
summary: 'Si vous utilisez FabricPool pour hiérarchiser les données vers StorageGRID, vous devez connaître les exigences de création des règles de gestion du cycle de vie des informations StorageGRID \(ILM\) et une politique ILM de gestion des données FabricPool. Vous devez veiller à ce que les règles ILM applicables aux données FabricPool ne soient pas perturbatrices.' 
---
= Utilisation de la solution de gestion du cycle de vie des informations StorageGRID avec les données FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez FabricPool pour hiérarchiser les données vers StorageGRID, vous devez connaître les exigences de création des règles StorageGRID de gestion du cycle de vie des informations (ILM) et une règle ILM de gestion des données FabricPool. Vous devez veiller à ce que les règles ILM applicables aux données FabricPool ne soient pas perturbatrices.

[IMPORTANT]
====
FabricPool ne connaît pas les règles ou les règles ILM de StorageGRID. La perte des données peut se produire si la règle ILM de StorageGRID est mal configurée.

Pour en savoir plus : link:../ilm/index.html["Gestion des objets avec ILM"]

====


== Instructions ILM pour les données FabricPool

Ces recommandations vous permettent de vérifier que vos règles ILM et votre politique ILM conviennent pour les données FabricPool et les exigences de votre entreprise. Si vous utilisez déjà la solution ILM de StorageGRID, vous devrez peut-être mettre à jour votre politique ILM active pour respecter ces directives.

* Vous pouvez utiliser toutes les combinaisons de réplication et de règles de code d'effacement pour protéger les données de Tier cloud.
+
Il est recommandé d'utiliser un code d'effacement 2+1 sur un site pour une protection des données économique. Le code d'effacement consomme plus de ressources de processeur, mais sa capacité de stockage est bien inférieure à la réplication. Les schémas 4+1 et 6+1 utilisent une capacité inférieure à 2+1, mais ils offrent un débit plus faible et une flexibilité moindre lorsque vous ajoutez des nœuds de stockage lors de l'extension du grid.

* Chaque règle appliquée aux données FabricPool doit au moins deux copies répliquées grâce au code d'effacement.
+

IMPORTANT: La règle ILM de création d'une seule copie répliquée pendant toute période met les données à risque de perte permanente. Si une seule copie répliquée d'un objet existe, cet objet est perdu en cas de défaillance ou d'erreur importante d'un noeud de stockage. De plus, lors des procédures de maintenance telles que les mises à niveau, l'accès à l'objet est temporairement perdu.

* N'utilisez pas de règle ILM pour supprimer ou expirer les données de niveau cloud FabricPool. Définissez la période de conservation de chaque règle ILM sur « Forever » afin d'assurer la suppression des objets FabricPool par StorageGRID ILM.
* Ne créez pas de règles pour déplacer les données FabricPool de Tier cloud depuis le compartiment vers un autre emplacement. Vous ne pouvez pas utiliser les règles ILM pour archiver les données FabricPool sur bande à l'aide d'un nœud d'archivage, ni utiliser un pool de stockage cloud pour les déplacer FabricPool vers Glacier.
+

NOTE: L'utilisation de pools de stockage cloud avec FabricPool n'est pas prise en charge en raison de la latence ajoutée pour extraire un objet de la cible du pool de stockage cloud.

* Depuis ONTAP 9.8, vous pouvez créer des balises d'objet pour classer et trier les données hiérarchisées pour simplifier la gestion. Par exemple, vous pouvez définir des balises uniquement sur les volumes FabricPool reliés à StorageGRID. Ensuite, lorsque vous créez des règles ILM dans StorageGRID, vous pouvez utiliser le filtre avancé balise d'objet pour sélectionner et placer ces données.

